/*
 Navicat Premium Data Transfer

 Source Server         : 192.168.1.99
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : 192.168.1.99:1521
 Source Schema         : APOLLOCONFIGDB

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 30/07/2020 19:51:07
*/


-- ----------------------------
-- Table structure for ACCESSKEY
-- ----------------------------
CREATE TABLE  ACCESSKEY (
  ID NUMBER NOT NULL ,
  APPID NVARCHAR2(500) DEFAULT 'default'  NOT NULL ,
  SECRET VARCHAR2(128 BYTE) DEFAULT 'default'  NOT NULL ,
  ISENABLED NUMBER(3) DEFAULT 0  NOT NULL ,
  ISDELETED NUMBER(3) DEFAULT 0  NOT NULL ,
  DATACHANGE_CREATEDBY VARCHAR2(32 BYTE) ,
  DATACHANGE_CREATEDTIME DATE NOT NULL ,
  DATACHANGE_LASTMODIFIEDBY VARCHAR2(32 BYTE) ,
  DATACHANGE_LASTTIME DATE
)
;
COMMENT ON COLUMN  ACCESSKEY.ID IS '主键ID';
COMMENT ON COLUMN  ACCESSKEY.APPID IS 'APPID';
COMMENT ON COLUMN  ACCESSKEY.SECRET IS 'Secret';
COMMENT ON COLUMN  ACCESSKEY.ISENABLED IS '启用标志：1: enabled, 0: disabled';
COMMENT ON COLUMN  ACCESSKEY.ISDELETED IS '删除标志：1: deleted, 0: normal';
COMMENT ON COLUMN  ACCESSKEY.DATACHANGE_CREATEDBY IS '创建人';
COMMENT ON COLUMN  ACCESSKEY.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN  ACCESSKEY.DATACHANGE_LASTMODIFIEDBY IS '最后修改人';
COMMENT ON COLUMN  ACCESSKEY.DATACHANGE_LASTTIME IS '最后修改时间';
COMMENT ON TABLE  ACCESSKEY IS '访问密钥';

-- ----------------------------
-- Table structure for APP
-- ----------------------------
CREATE TABLE  APP (
  ID NUMBER NOT NULL ,
  APPID VARCHAR2(500 BYTE) DEFAULT 'default'  NOT NULL ,
  NAME VARCHAR2(500 BYTE) DEFAULT 'default'  NOT NULL ,
  ORGID VARCHAR2(32 BYTE) DEFAULT 'default'  NOT NULL ,
  ORGNAME VARCHAR2(64 BYTE) DEFAULT 'default'  NOT NULL ,
  OWNERNAME VARCHAR2(500 BYTE) DEFAULT 'default'  NOT NULL ,
  OWNEREMAIL VARCHAR2(500 BYTE) DEFAULT 'default'  NOT NULL ,
  ISDELETED NUMBER(3) DEFAULT 0  NOT NULL ,
  DATACHANGE_CREATEDBY VARCHAR2(32 BYTE) ,
  DATACHANGE_CREATEDTIME DATE NOT NULL ,
  DATACHANGE_LASTMODIFIEDBY VARCHAR2(32 BYTE) ,
  DATACHANGE_LASTTIME DATE
)
;
COMMENT ON COLUMN  APP.ID IS '主键';
COMMENT ON COLUMN  APP.APPID IS 'APPID';
COMMENT ON COLUMN  APP.NAME IS '应用名';
COMMENT ON COLUMN  APP.ORGID IS '部门Id';
COMMENT ON COLUMN  APP.ORGNAME IS '部门名字';
COMMENT ON COLUMN  APP.OWNERNAME IS 'ownerName';
COMMENT ON COLUMN  APP.OWNEREMAIL IS 'ownerEmail';
COMMENT ON COLUMN  APP.ISDELETED IS '删除标志：1: deleted, 0: normal';
COMMENT ON COLUMN  APP.DATACHANGE_CREATEDBY IS '创建人';
COMMENT ON COLUMN  APP.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN  APP.DATACHANGE_LASTMODIFIEDBY IS '最后修改人';
COMMENT ON COLUMN  APP.DATACHANGE_LASTTIME IS '最后修改时间';
COMMENT ON TABLE  APP IS '应用表';

-- ----------------------------
-- Records of APP
-- ----------------------------
INSERT INTO  APP VALUES ('1', 'SampleApp', 'Sample App', 'TEST1', '样例部门1', 'apollo', 'apollo@acme.com', '0', 'default', TO_DATE('2017-09-11 15:41:26', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2017-09-11 15:41:26', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for APPNAMESPACE
-- ----------------------------
CREATE TABLE  APPNAMESPACE (
  ID NUMBER NOT NULL ,
  NAME VARCHAR2(32 BYTE) NOT NULL ,
  APPID VARCHAR2(32 BYTE) NOT NULL ,
  FORMAT VARCHAR2(32 BYTE) DEFAULT 'properties'  NOT NULL ,
  ISPUBLIC NUMBER(3) DEFAULT 0  NOT NULL ,
  COMMT VARCHAR2(64 BYTE) ,
  ISDELETED NUMBER(3) DEFAULT 0  NOT NULL ,
  DATACHANGE_CREATEDBY VARCHAR2(32 BYTE) ,
  DATACHANGE_CREATEDTIME DATE NOT NULL ,
  DATACHANGE_LASTMODIFIEDBY VARCHAR2(32 BYTE) ,
  DATACHANGE_LASTTIME DATE
)
;
COMMENT ON COLUMN  APPNAMESPACE.ID IS '主键';
COMMENT ON COLUMN  APPNAMESPACE.NAME IS 'namespace名字，注意，需要全局唯一';
COMMENT ON COLUMN  APPNAMESPACE.APPID IS 'APPID';
COMMENT ON COLUMN  APPNAMESPACE.FORMAT IS 'namespace的format类型';
COMMENT ON COLUMN  APPNAMESPACE.ISPUBLIC IS 'namespace是否为公共';
COMMENT ON COLUMN  APPNAMESPACE.COMMT IS '注释';
COMMENT ON COLUMN  APPNAMESPACE.ISDELETED IS '删除标志：1: deleted, 0: normal';
COMMENT ON COLUMN  APPNAMESPACE.DATACHANGE_CREATEDBY IS '创建人';
COMMENT ON COLUMN  APPNAMESPACE.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN  APPNAMESPACE.DATACHANGE_LASTMODIFIEDBY IS '最后修改人';
COMMENT ON COLUMN  APPNAMESPACE.DATACHANGE_LASTTIME IS '最后修改时间';
COMMENT ON TABLE  APPNAMESPACE IS '应用命名空间';

-- ----------------------------
-- Records of APPNAMESPACE
-- ----------------------------
INSERT INTO  APPNAMESPACE VALUES ('1', 'application', 'SampleApp', 'properties', '0', 'default app namespace', '0', NULL, TO_DATE('2017-09-11 15:41:27', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2017-09-11 15:41:27', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for AUDIT_TABLE
-- ----------------------------
CREATE TABLE  AUDIT_TABLE (
  ID NUMBER NOT NULL ,
  ENTITYNAME VARCHAR2(50 BYTE) DEFAULT 'default'  NOT NULL ,
  ENTITYID NUMBER ,
  OPNAME VARCHAR2(50 BYTE) DEFAULT 'default'  NOT NULL ,
  COMMT VARCHAR2(500 BYTE) ,
  ISDELETED NUMBER(3) DEFAULT 0  NOT NULL ,
  DATACHANGE_CREATEDBY VARCHAR2(32 BYTE) ,
  DATACHANGE_CREATEDTIME DATE NOT NULL ,
  DATACHANGE_LASTMODIFIEDBY VARCHAR2(32 BYTE) ,
  DATACHANGE_LASTTIME DATE
)
;
COMMENT ON COLUMN  AUDIT_TABLE.ID IS '主键';
COMMENT ON COLUMN  AUDIT_TABLE.ENTITYNAME IS '表名';
COMMENT ON COLUMN  AUDIT_TABLE.ENTITYID IS '记录ID';
COMMENT ON COLUMN  AUDIT_TABLE.OPNAME IS '操作类型';
COMMENT ON COLUMN  AUDIT_TABLE.COMMT IS '备注';
COMMENT ON COLUMN  AUDIT_TABLE.ISDELETED IS '删除标志：1: deleted, 0: normal';
COMMENT ON COLUMN  AUDIT_TABLE.DATACHANGE_CREATEDBY IS '创建人';
COMMENT ON COLUMN  AUDIT_TABLE.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN  AUDIT_TABLE.DATACHANGE_LASTMODIFIEDBY IS '最后修改人';
COMMENT ON COLUMN  AUDIT_TABLE.DATACHANGE_LASTTIME IS '最后修改时间';
COMMENT ON TABLE  AUDIT_TABLE IS '日志审计表';

-- ----------------------------
-- Table structure for CLUSTER_TABLE
-- ----------------------------
CREATE TABLE  CLUSTER_TABLE (
  ID NUMBER NOT NULL ,
  NAME VARCHAR2(32 BYTE) NOT NULL ,
  APPID VARCHAR2(32 BYTE) NOT NULL ,
  PARENTCLUSTERID NUMBER DEFAULT 0  NOT NULL ,
  ISDELETED NUMBER(3) DEFAULT 0  NOT NULL ,
  DATACHANGE_CREATEDBY VARCHAR2(32 BYTE) ,
  DATACHANGE_CREATEDTIME DATE NOT NULL ,
  DATACHANGE_LASTMODIFIEDBY VARCHAR2(32 BYTE) ,
  DATACHANGE_LASTTIME DATE
)
;
COMMENT ON COLUMN  CLUSTER_TABLE.ID IS '主键';
COMMENT ON COLUMN  CLUSTER_TABLE.NAME IS '集群名字';
COMMENT ON COLUMN  CLUSTER_TABLE.APPID IS 'APPID';
COMMENT ON COLUMN  CLUSTER_TABLE.PARENTCLUSTERID IS '父cluster';
COMMENT ON COLUMN  CLUSTER_TABLE.ISDELETED IS '删除标志：1: deleted, 0: normal';
COMMENT ON COLUMN  CLUSTER_TABLE.DATACHANGE_CREATEDBY IS '创建人';
COMMENT ON COLUMN  CLUSTER_TABLE.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN  CLUSTER_TABLE.DATACHANGE_LASTMODIFIEDBY IS '最后修改人';
COMMENT ON COLUMN  CLUSTER_TABLE.DATACHANGE_LASTTIME IS '最后修改时间';
COMMENT ON TABLE  CLUSTER_TABLE IS '集群';

-- ----------------------------
-- Records of CLUSTER_TABLE
-- ----------------------------
INSERT INTO  CLUSTER_TABLE VALUES ('1', 'default', 'SampleApp', '0', '0', NULL, TO_DATE('2017-09-11 15:41:27', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2017-09-11 15:41:27', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for COMMIT
-- ----------------------------
CREATE TABLE  COMMIT (
  ID NUMBER NOT NULL ,
  CHANGESETS CLOB ,
  APPID VARCHAR2(500 BYTE) DEFAULT 'default'  NOT NULL ,
  CLUSTERNAME VARCHAR2(500 BYTE) DEFAULT 'default'  NOT NULL ,
  NAMESPACENAME VARCHAR2(500 BYTE) DEFAULT 'default'  NOT NULL ,
  COMMT VARCHAR2(500 BYTE) ,
  ISDELETED NUMBER(3) DEFAULT 0  NOT NULL ,
  DATACHANGE_CREATEDBY VARCHAR2(32 BYTE) ,
  DATACHANGE_CREATEDTIME DATE NOT NULL ,
  DATACHANGE_LASTMODIFIEDBY VARCHAR2(32 BYTE) ,
  DATACHANGE_LASTTIME DATE
)
;
COMMENT ON COLUMN  COMMIT.ID IS '主键';
COMMENT ON COLUMN  COMMIT.CHANGESETS IS '修改变更集';
COMMENT ON COLUMN  COMMIT.APPID IS 'APPID';
COMMENT ON COLUMN  COMMIT.CLUSTERNAME IS 'ClusterName';
COMMENT ON COLUMN  COMMIT.NAMESPACENAME IS 'namespaceName';
COMMENT ON COLUMN  COMMIT.COMMT IS '备注';
COMMENT ON COLUMN  COMMIT.ISDELETED IS '删除标志：1: deleted, 0: normal';
COMMENT ON COLUMN  COMMIT.DATACHANGE_CREATEDBY IS '创建人';
COMMENT ON COLUMN  COMMIT.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN  COMMIT.DATACHANGE_LASTMODIFIEDBY IS '最后修改人';
COMMENT ON COLUMN  COMMIT.DATACHANGE_LASTTIME IS '最后修改时间';
COMMENT ON TABLE  COMMIT IS 'commit历史表';

-- ----------------------------
-- Table structure for GRAYRELEASERULE
-- ----------------------------
CREATE TABLE  GRAYRELEASERULE (
  ID NUMBER NOT NULL ,
  APPID VARCHAR2(32 BYTE) DEFAULT 'default'  NOT NULL ,
  CLUSTERNAME VARCHAR2(32 BYTE) DEFAULT 'default'  NOT NULL ,
  NAMESPACENAME VARCHAR2(32 BYTE) DEFAULT 'default'  NOT NULL ,
  BRANCHNAME VARCHAR2(32 BYTE) DEFAULT 'default'  NOT NULL ,
  RULES VARCHAR2(1600 BYTE) DEFAULT '[]' ,
  RELEASEID NUMBER DEFAULT 0  NOT NULL ,
  BRANCHSTATUS NUMBER(3) DEFAULT 1 ,
  ISDELETED NUMBER(3) DEFAULT 0  NOT NULL ,
  DATACHANGE_CREATEDBY VARCHAR2(32 BYTE) DEFAULT 'default'  ,
  DATACHANGE_CREATEDTIME DATE NOT NULL ,
  DATACHANGE_LASTMODIFIEDBY VARCHAR2(32 BYTE) ,
  DATACHANGE_LASTTIME DATE
)
;
COMMENT ON COLUMN  GRAYRELEASERULE.ID IS '主键';
COMMENT ON COLUMN  GRAYRELEASERULE.APPID IS 'AppID';
COMMENT ON COLUMN  GRAYRELEASERULE.CLUSTERNAME IS 'Cluster Name';
COMMENT ON COLUMN  GRAYRELEASERULE.NAMESPACENAME IS 'Namespace Name';
COMMENT ON COLUMN  GRAYRELEASERULE.BRANCHNAME IS 'branch name';
COMMENT ON COLUMN  GRAYRELEASERULE.RULES IS '灰度规则';
COMMENT ON COLUMN  GRAYRELEASERULE.RELEASEID IS '灰度对应的release';
COMMENT ON COLUMN  GRAYRELEASERULE.BRANCHSTATUS IS '灰度分支状态: 0:删除分支,1:正在使用的规则 2：全量发布';
COMMENT ON COLUMN  GRAYRELEASERULE.ISDELETED IS '删除标志：1: deleted, 0: normal';
COMMENT ON COLUMN  GRAYRELEASERULE.DATACHANGE_CREATEDBY IS '创建人';
COMMENT ON COLUMN  GRAYRELEASERULE.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN  GRAYRELEASERULE.DATACHANGE_LASTMODIFIEDBY IS '最后修改人';
COMMENT ON COLUMN  GRAYRELEASERULE.DATACHANGE_LASTTIME IS '最后修改时间';
COMMENT ON TABLE  GRAYRELEASERULE IS '灰度规则表';

-- ----------------------------
-- Table structure for INSTANCE
-- ----------------------------
CREATE TABLE  INSTANCE (
  ID NUMBER NOT NULL ,
  APPID VARCHAR2(32 BYTE) DEFAULT 'default'  NOT NULL ,
  CLUSTERNAME VARCHAR2(32 BYTE) DEFAULT 'default'  NOT NULL ,
  DATACENTER VARCHAR2(64 BYTE) DEFAULT 'default' ,
  IP VARCHAR2(32 BYTE) NOT NULL ,
  DATACHANGE_CREATEDTIME DATE NOT NULL ,
  DATACHANGE_LASTTIME DATE NOT NULL
)
;
COMMENT ON COLUMN  INSTANCE.ID IS '主键';
COMMENT ON COLUMN  INSTANCE.APPID IS 'AppID';
COMMENT ON COLUMN  INSTANCE.CLUSTERNAME IS 'Cluster Name';
COMMENT ON COLUMN  INSTANCE.DATACENTER IS 'Data Center Name';
COMMENT ON COLUMN  INSTANCE.IP IS 'instance ip';
COMMENT ON COLUMN  INSTANCE.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN  INSTANCE.DATACHANGE_LASTTIME IS '最后修改时间';
COMMENT ON TABLE  INSTANCE IS '使用配置的应用实例';

-- ----------------------------
-- Table structure for INSTANCECONFIG
-- ----------------------------
CREATE TABLE  INSTANCECONFIG (
  ID NUMBER NOT NULL ,
  INSTANCEID NUMBER ,
  CONFIGAPPID VARCHAR2(32 BYTE) DEFAULT 'default'  NOT NULL ,
  CONFIGCLUSTERNAME VARCHAR2(32 BYTE) DEFAULT 'default'  NOT NULL ,
  CONFIGNAMESPACENAME VARCHAR2(32 BYTE) DEFAULT 'default'  NOT NULL ,
  RELEASEKEY VARCHAR2(64 BYTE) NOT NULL ,
  RELEASEDELIVERYTIME DATE ,
  DATACHANGE_CREATEDTIME DATE NOT NULL ,
  DATACHANGE_LASTTIME DATE NOT NULL
)
;
COMMENT ON COLUMN  INSTANCECONFIG.ID IS '主键';
COMMENT ON COLUMN  INSTANCECONFIG.INSTANCEID IS 'Instance Id';
COMMENT ON COLUMN  INSTANCECONFIG.CONFIGAPPID IS 'Config App Id';
COMMENT ON COLUMN  INSTANCECONFIG.CONFIGCLUSTERNAME IS 'Config Cluster Name';
COMMENT ON COLUMN  INSTANCECONFIG.CONFIGNAMESPACENAME IS 'Config Namespace Name';
COMMENT ON COLUMN  INSTANCECONFIG.RELEASEKEY IS '发布的Key';
COMMENT ON COLUMN  INSTANCECONFIG.RELEASEDELIVERYTIME IS '配置获取时间';
COMMENT ON COLUMN  INSTANCECONFIG.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN  INSTANCECONFIG.DATACHANGE_LASTTIME IS '最后修改时间';
COMMENT ON TABLE  INSTANCECONFIG IS '应用实例的配置信息';

-- ----------------------------
-- Table structure for ITEM
-- ----------------------------
CREATE TABLE  ITEM (
  ID NUMBER NOT NULL ,
  NAMESPACEID NUMBER DEFAULT 0  NOT NULL ,
  KEY_COL VARCHAR2(128 BYTE) DEFAULT 'default'  NOT NULL ,
  VALUE_COL CLOB ,
  COMMT VARCHAR2(1024 BYTE) ,
  LINENUM NUMBER DEFAULT 0 ,
  ISDELETED NUMBER(3) DEFAULT 0  NOT NULL ,
  DATACHANGE_CREATEDBY VARCHAR2(32 BYTE) ,
  DATACHANGE_CREATEDTIME DATE NOT NULL ,
  DATACHANGE_LASTMODIFIEDBY VARCHAR2(32 BYTE) ,
  DATACHANGE_LASTTIME DATE
)
;
COMMENT ON COLUMN  ITEM.ID IS '主键';
COMMENT ON COLUMN  ITEM.NAMESPACEID IS '集群NamespaceId';
COMMENT ON COLUMN  ITEM.KEY_COL IS '配置项Key';
COMMENT ON COLUMN  ITEM.VALUE_COL IS '配置项值';
COMMENT ON COLUMN  ITEM.COMMT IS '注释';
COMMENT ON COLUMN  ITEM.LINENUM IS '行号';
COMMENT ON COLUMN  ITEM.ISDELETED IS '删除标志：1: deleted, 0: normal';
COMMENT ON COLUMN  ITEM.DATACHANGE_CREATEDBY IS '创建人';
COMMENT ON COLUMN  ITEM.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN  ITEM.DATACHANGE_LASTMODIFIEDBY IS '最后修改人';
COMMENT ON COLUMN  ITEM.DATACHANGE_LASTTIME IS '最后修改时间';
COMMENT ON TABLE  ITEM IS '配置项目';

-- ----------------------------
-- Records of ITEM
-- ----------------------------
INSERT INTO  ITEM VALUES ('1', '1', 'timeout', '100', 'sample timeout配置', '1', '0', 'default', TO_DATE('2017-09-11 15:41:27', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2017-09-11 15:41:27', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for NAMESPACE
-- ----------------------------
CREATE TABLE  NAMESPACE (
  ID NUMBER NOT NULL ,
  APPID VARCHAR2(500 BYTE) DEFAULT 'default'  NOT NULL ,
  CLUSTERNAME VARCHAR2(500 BYTE) DEFAULT 'default'  NOT NULL ,
  NAMESPACENAME VARCHAR2(500 BYTE) DEFAULT 'default'  NOT NULL ,
  ISDELETED NUMBER(3) DEFAULT 0  NOT NULL ,
  DATACHANGE_CREATEDBY VARCHAR2(32 BYTE) NOT NULL ,
  DATACHANGE_CREATEDTIME DATE NOT NULL ,
  DATACHANGE_LASTMODIFIEDBY VARCHAR2(32 BYTE) ,
  DATACHANGE_LASTTIME DATE
)
;
COMMENT ON COLUMN  NAMESPACE.ID IS '主键';
COMMENT ON COLUMN  NAMESPACE.APPID IS 'AppID';
COMMENT ON COLUMN  NAMESPACE.CLUSTERNAME IS 'Cluster Name';
COMMENT ON COLUMN  NAMESPACE.NAMESPACENAME IS 'Namespace Name';
COMMENT ON COLUMN  NAMESPACE.ISDELETED IS '删除标志：1: deleted, 0: normal';
COMMENT ON COLUMN  NAMESPACE.DATACHANGE_CREATEDBY IS '创建人';
COMMENT ON COLUMN  NAMESPACE.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN  NAMESPACE.DATACHANGE_LASTMODIFIEDBY IS '最后修改人';
COMMENT ON COLUMN  NAMESPACE.DATACHANGE_LASTTIME IS '最后修改时间';
COMMENT ON TABLE  NAMESPACE IS '命名空间';

-- ----------------------------
-- Records of NAMESPACE
-- ----------------------------
INSERT INTO  NAMESPACE VALUES ('1', 'SampleApp', 'default', 'application', '0', 'default', TO_DATE('2017-09-11 15:41:27', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2017-09-11 15:41:27', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for NAMESPACELOCK
-- ----------------------------
CREATE TABLE  NAMESPACELOCK (
  ID NUMBER NOT NULL ,
  NAMESPACEID NUMBER DEFAULT 0  NOT NULL ,
  ISDELETED NUMBER(3) DEFAULT 0  NOT NULL ,
  DATACHANGE_CREATEDBY VARCHAR2(32 BYTE) ,
  DATACHANGE_CREATEDTIME DATE NOT NULL ,
  DATACHANGE_LASTMODIFIEDBY VARCHAR2(32 BYTE) ,
  DATACHANGE_LASTTIME DATE
)
;
COMMENT ON COLUMN  NAMESPACELOCK.ID IS '主键';
COMMENT ON COLUMN  NAMESPACELOCK.NAMESPACEID IS '集群NamespaceId';
COMMENT ON COLUMN  NAMESPACELOCK.ISDELETED IS '删除标志：1: deleted, 0: normal';
COMMENT ON COLUMN  NAMESPACELOCK.DATACHANGE_CREATEDBY IS '创建人';
COMMENT ON COLUMN  NAMESPACELOCK.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN  NAMESPACELOCK.DATACHANGE_LASTMODIFIEDBY IS '最后修改人';
COMMENT ON COLUMN  NAMESPACELOCK.DATACHANGE_LASTTIME IS '最后修改时间';
COMMENT ON TABLE  NAMESPACELOCK IS '命名空间编辑锁';

-- ----------------------------
-- Table structure for RELEASEHISTORY
-- ----------------------------
CREATE TABLE  RELEASEHISTORY (
  ID NUMBER NOT NULL ,
  APPID VARCHAR2(32 BYTE) DEFAULT 'default'  NOT NULL ,
  CLUSTERNAME VARCHAR2(32 BYTE) DEFAULT 'default'  NOT NULL ,
  NAMESPACENAME VARCHAR2(32 BYTE) DEFAULT 'default'  NOT NULL ,
  BRANCHNAME VARCHAR2(32 BYTE) DEFAULT 'default'  NOT NULL ,
  RELEASEID NUMBER DEFAULT 0  NOT NULL ,
  PREVIOUSRELEASEID NUMBER DEFAULT 0  NOT NULL ,
  OPERATION NUMBER(5) DEFAULT 0  NOT NULL ,
  OPERATIONCONTEXT CLOB ,
  ISDELETED NUMBER(3) DEFAULT 0  NOT NULL ,
  DATACHANGE_CREATEDBY VARCHAR2(32 BYTE) ,
  DATACHANGE_CREATEDTIME DATE NOT NULL ,
  DATACHANGE_LASTMODIFIEDBY VARCHAR2(32 BYTE) ,
  DATACHANGE_LASTTIME DATE
)
;
COMMENT ON COLUMN  RELEASEHISTORY.ID IS '主键';
COMMENT ON COLUMN  RELEASEHISTORY.APPID IS 'AppID';
COMMENT ON COLUMN  RELEASEHISTORY.CLUSTERNAME IS 'ClusterName';
COMMENT ON COLUMN  RELEASEHISTORY.NAMESPACENAME IS 'namespaceName';
COMMENT ON COLUMN  RELEASEHISTORY.BRANCHNAME IS '发布分支名';
COMMENT ON COLUMN  RELEASEHISTORY.RELEASEID IS '关联的Release Id';
COMMENT ON COLUMN  RELEASEHISTORY.PREVIOUSRELEASEID IS '前一次发布的ReleaseId';
COMMENT ON COLUMN  RELEASEHISTORY.OPERATION IS '发布类型，0: 普通发布，1: 回滚，2: 灰度发布，3: 灰度规则更新，4: 灰度合并回主分支发布，5: 主分支发布灰度自动发布，6: 主分支回滚灰度自动发布，7: 放弃灰度';
COMMENT ON COLUMN  RELEASEHISTORY.OPERATIONCONTEXT IS '发布上下文信息';
COMMENT ON COLUMN  RELEASEHISTORY.ISDELETED IS '删除标志：1: deleted, 0: normal';
COMMENT ON COLUMN  RELEASEHISTORY.DATACHANGE_CREATEDBY IS '创建人';
COMMENT ON COLUMN  RELEASEHISTORY.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN  RELEASEHISTORY.DATACHANGE_LASTMODIFIEDBY IS '最后修改人';
COMMENT ON COLUMN  RELEASEHISTORY.DATACHANGE_LASTTIME IS '最后修改时间';
COMMENT ON TABLE  RELEASEHISTORY IS '发布历史';

-- ----------------------------
-- Records of RELEASEHISTORY
-- ----------------------------
INSERT INTO  RELEASEHISTORY VALUES ('1', 'SampleApp', 'default', 'application', 'default', '1', '0', '0', '{}', '0', 'apollo', TO_DATE('2017-09-11 15:41:28', 'SYYYY-MM-DD HH24:MI:SS'), 'apollo', TO_DATE('2017-09-11 15:41:28', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for RELEASEMESSAGE
-- ----------------------------
CREATE TABLE  RELEASEMESSAGE (
  ID NUMBER NOT NULL ,
  MESSAGE VARCHAR2(1024 BYTE) NOT NULL ,
  DATACHANGE_LASTTIME DATE NOT NULL
)
;
COMMENT ON COLUMN  RELEASEMESSAGE.ID IS '主键';
COMMENT ON COLUMN  RELEASEMESSAGE.MESSAGE IS '发布的消息内容';
COMMENT ON COLUMN  RELEASEMESSAGE.DATACHANGE_LASTTIME IS '最后修改时间';
COMMENT ON TABLE  RELEASEMESSAGE IS '发布消息';

-- ----------------------------
-- Table structure for RELEASE_TABLE
-- ----------------------------
CREATE TABLE  RELEASE_TABLE (
  ID NUMBER NOT NULL ,
  RELEASEKEY VARCHAR2(64 BYTE) NOT NULL ,
  NAME VARCHAR2(64 BYTE) DEFAULT 'default'  NOT NULL ,
  COMMT VARCHAR2(256 BYTE) ,
  APPID VARCHAR2(500 BYTE) DEFAULT 'default'  NOT NULL ,
  CLUSTERNAME VARCHAR2(500 BYTE) DEFAULT 'default'  NOT NULL ,
  NAMESPACENAME VARCHAR2(500 BYTE) DEFAULT 'default'  NOT NULL ,
  CONFIGURATIONS CLOB ,
  ISABANDONED NUMBER(3) DEFAULT 0  NOT NULL ,
  ISDELETED NUMBER(3) DEFAULT 0  NOT NULL ,
  DATACHANGE_CREATEDBY VARCHAR2(32 BYTE) ,
  DATACHANGE_CREATEDTIME DATE NOT NULL ,
  DATACHANGE_LASTMODIFIEDBY VARCHAR2(32 BYTE) ,
  DATACHANGE_LASTTIME DATE
)
;
COMMENT ON COLUMN  RELEASE_TABLE.ID IS '主键';
COMMENT ON COLUMN  RELEASE_TABLE.RELEASEKEY IS '发布的Key';
COMMENT ON COLUMN  RELEASE_TABLE.NAME IS '发布名字';
COMMENT ON COLUMN  RELEASE_TABLE.COMMT IS '发布说明';
COMMENT ON COLUMN  RELEASE_TABLE.APPID IS 'AppID';
COMMENT ON COLUMN  RELEASE_TABLE.CLUSTERNAME IS 'ClusterName';
COMMENT ON COLUMN  RELEASE_TABLE.NAMESPACENAME IS 'namespaceName';
COMMENT ON COLUMN  RELEASE_TABLE.CONFIGURATIONS IS '发布配置';
COMMENT ON COLUMN  RELEASE_TABLE.ISABANDONED IS '是否废弃,1: abandoned, 0: normal';
COMMENT ON COLUMN  RELEASE_TABLE.ISDELETED IS '删除标志：1: deleted, 0: normal';
COMMENT ON COLUMN  RELEASE_TABLE.DATACHANGE_CREATEDBY IS '创建人';
COMMENT ON COLUMN  RELEASE_TABLE.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN  RELEASE_TABLE.DATACHANGE_LASTMODIFIEDBY IS '最后修改人';
COMMENT ON COLUMN  RELEASE_TABLE.DATACHANGE_LASTTIME IS '最后修改时间';
COMMENT ON TABLE  RELEASE_TABLE IS '发布';

-- ----------------------------
-- Records of RELEASE_TABLE
-- ----------------------------
INSERT INTO  RELEASE_TABLE VALUES ('1', '20161009155425-d3a0749c6e20bc15', '20161009155424-release', 'Sample发布', 'SampleApp', 'default', 'application', '{timeout:100}', '0', '0', 'default', TO_DATE('2017-09-11 15:41:28', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2017-09-11 15:41:28', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for SERVERCONFIG
-- ----------------------------
CREATE TABLE  SERVERCONFIG (
  ID NUMBER NOT NULL ,
  KEY_COL VARCHAR2(64 BYTE) DEFAULT 'default'  NOT NULL ,
  CLUSTER_COL VARCHAR2(32 BYTE) DEFAULT 'default'  NOT NULL ,
  VALUE_COL VARCHAR2(500 BYTE) ,
  COMMT VARCHAR2(1024 BYTE) ,
  ISDELETED NUMBER(3) DEFAULT 0  NOT NULL ,
  DATACHANGE_CREATEDBY VARCHAR2(32 BYTE) ,
  DATACHANGE_CREATEDTIME DATE NOT NULL ,
  DATACHANGE_LASTMODIFIEDBY VARCHAR2(32 BYTE) ,
  DATACHANGE_LASTTIME DATE
)
;
COMMENT ON COLUMN  SERVERCONFIG.ID IS '主键';
COMMENT ON COLUMN  SERVERCONFIG.KEY_COL IS '配置项Key';
COMMENT ON COLUMN  SERVERCONFIG.CLUSTER_COL IS '配置对应的集群，default为不针对特定的集群';
COMMENT ON COLUMN  SERVERCONFIG.VALUE_COL IS '配置项值';
COMMENT ON COLUMN  SERVERCONFIG.COMMT IS '注释';
COMMENT ON COLUMN  SERVERCONFIG.ISDELETED IS '删除标志：1: deleted, 0: normal';
COMMENT ON COLUMN  SERVERCONFIG.DATACHANGE_CREATEDBY IS '创建人';
COMMENT ON COLUMN  SERVERCONFIG.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN  SERVERCONFIG.DATACHANGE_LASTMODIFIEDBY IS '最后修改人';
COMMENT ON COLUMN  SERVERCONFIG.DATACHANGE_LASTTIME IS '最后修改时间';
COMMENT ON TABLE  SERVERCONFIG IS '发布历史';

-- ----------------------------
-- Records of SERVERCONFIG
-- ----------------------------
INSERT INTO  SERVERCONFIG VALUES ('1', 'eureka.service.url', 'default', 'http://127.0.0.1:6166/eureka/', 'Eureka服务Url', '0', 'default', TO_DATE('2017-09-11 15:41:26', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2017-09-12 14:41:58', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO  SERVERCONFIG VALUES ('2', 'namespace.lock.switch', 'default', 'false', '一次发布只能有一个人修改开关', '0', 'default', TO_DATE('2017-09-11 15:41:26', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2017-09-11 15:41:26', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO  SERVERCONFIG VALUES ('3', 'item.value.length.limit', 'default', '20000', 'item value最大长度限制', '0', 'default', TO_DATE('2017-09-11 15:41:26', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2017-09-11 15:41:26', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO  SERVERCONFIG VALUES ('4', 'appnamespace.private.enable', 'default', 'false', '是否开启private namespace', '0', 'default', TO_DATE('2017-09-11 15:41:26', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2017-09-11 15:41:26', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO  SERVERCONFIG VALUES ('5', 'item.key.length.limit', 'default', '128', 'item key 最大长度限制', '0', 'default', TO_DATE('2017-09-11 15:41:26', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2017-09-11 15:41:26', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for SYS_ID_MACHINE
-- ----------------------------
CREATE TABLE  SYS_ID_MACHINE (
  MACHINE_IP NVARCHAR2(16) NOT NULL ,
  MACHINE_ID NUMBER(11) NOT NULL ,
  ADD_TIME DATE NOT NULL ,
  HEART_LAST_TIME DATE NOT NULL
)
;
COMMENT ON COLUMN  SYS_ID_MACHINE.MACHINE_IP IS '主机IP';
COMMENT ON COLUMN  SYS_ID_MACHINE.MACHINE_ID IS '主机IP对应的机器码';
COMMENT ON COLUMN  SYS_ID_MACHINE.ADD_TIME IS '创建时间';
COMMENT ON COLUMN  SYS_ID_MACHINE.HEART_LAST_TIME IS '最后一次心跳时间';

-- ----------------------------
-- Primary Key structure for table ACCESSKEY
-- ----------------------------
ALTER TABLE  ACCESSKEY ADD CONSTRAINT AC_PRIMARY00000 PRIMARY KEY (ID);

-- ----------------------------
-- Checks structure for table ACCESSKEY
-- ----------------------------
ALTER TABLE  ACCESSKEY ADD CONSTRAINT AC_SYS_C0028502 CHECK (ID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  ACCESSKEY ADD CONSTRAINT AC_SYS_C0028503 CHECK (APPID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  ACCESSKEY ADD CONSTRAINT AC_SYS_C0028504 CHECK (SECRET IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  ACCESSKEY ADD CONSTRAINT AC_SYS_C0028505 CHECK (ISENABLED IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  ACCESSKEY ADD CONSTRAINT AC_SYS_C0028506 CHECK (ISDELETED IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  ACCESSKEY ADD CONSTRAINT AC_SYS_C0028507 CHECK (DATACHANGE_CREATEDTIME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table ACCESSKEY
-- ----------------------------
CREATE INDEX  AC_APPID00000
  ON  ACCESSKEY (APPID ASC);
CREATE INDEX  DATACHANGE_LASTTIME00000
  ON  ACCESSKEY (DATACHANGE_LASTTIME ASC);

-- ----------------------------
-- Primary Key structure for table APP
-- ----------------------------
ALTER TABLE  APP ADD CONSTRAINT AC_PRIMARY00001 PRIMARY KEY (ID);

-- ----------------------------
-- Checks structure for table APP
-- ----------------------------
ALTER TABLE  APP ADD CONSTRAINT AC_SYS_C0028509 CHECK (ID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  APP ADD CONSTRAINT AC_SYS_C0028510 CHECK (APPID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  APP ADD CONSTRAINT AC_SYS_C0028511 CHECK (NAME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  APP ADD CONSTRAINT AC_SYS_C0028512 CHECK (ORGID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  APP ADD CONSTRAINT AC_SYS_C0028513 CHECK (ORGNAME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  APP ADD CONSTRAINT AC_SYS_C0028514 CHECK (OWNERNAME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  APP ADD CONSTRAINT AC_SYS_C0028515 CHECK (OWNEREMAIL IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  APP ADD CONSTRAINT AC_SYS_C0028516 CHECK (ISDELETED IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  APP ADD CONSTRAINT AC_SYS_C0028517 CHECK (DATACHANGE_CREATEDTIME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table APP
-- ----------------------------
CREATE INDEX  AC_APPID00001
  ON  APP (APPID ASC);
CREATE INDEX  AC_DATACHANGE_LASTTIME00001
  ON  APP (DATACHANGE_LASTTIME ASC);

-- ----------------------------
-- Primary Key structure for table APPNAMESPACE
-- ----------------------------
ALTER TABLE  APPNAMESPACE ADD CONSTRAINT AC_PRIMARY00002 PRIMARY KEY (ID);

-- ----------------------------
-- Checks structure for table APPNAMESPACE
-- ----------------------------
ALTER TABLE  APPNAMESPACE ADD CONSTRAINT AC_SYS_C0028519 CHECK (ID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  APPNAMESPACE ADD CONSTRAINT AC_SYS_C0028520 CHECK (NAME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  APPNAMESPACE ADD CONSTRAINT AC_SYS_C0028521 CHECK (APPID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  APPNAMESPACE ADD CONSTRAINT AC_SYS_C0028522 CHECK (FORMAT IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  APPNAMESPACE ADD CONSTRAINT AC_SYS_C0028523 CHECK (ISPUBLIC IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  APPNAMESPACE ADD CONSTRAINT AC_SYS_C0028524 CHECK (ISDELETED IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  APPNAMESPACE ADD CONSTRAINT AC_SYS_C0028525 CHECK (DATACHANGE_CREATEDTIME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table APPNAMESPACE
-- ----------------------------
CREATE INDEX  AC_DATACHANGE_LASTTIME00002
  ON  APPNAMESPACE (DATACHANGE_LASTTIME ASC);
CREATE INDEX  AC_IX_APPID
  ON  APPNAMESPACE (APPID ASC);
CREATE INDEX  AC_NAME_APPID
  ON  APPNAMESPACE (NAME ASC, APPID ASC);

-- ----------------------------
-- Primary Key structure for table AUDIT_TABLE
-- ----------------------------
ALTER TABLE  AUDIT_TABLE ADD CONSTRAINT AC_PRIMARY00003 PRIMARY KEY (ID);

-- ----------------------------
-- Checks structure for table AUDIT_TABLE
-- ----------------------------
ALTER TABLE  AUDIT_TABLE ADD CONSTRAINT AC_SYS_C0028527 CHECK (ID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  AUDIT_TABLE ADD CONSTRAINT AC_SYS_C0028528 CHECK (ENTITYNAME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  AUDIT_TABLE ADD CONSTRAINT AC_SYS_C0028529 CHECK (OPNAME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  AUDIT_TABLE ADD CONSTRAINT AC_SYS_C0028530 CHECK (ISDELETED IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  AUDIT_TABLE ADD CONSTRAINT AC_SYS_C0028531 CHECK (DATACHANGE_CREATEDTIME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table AUDIT_TABLE
-- ----------------------------
CREATE INDEX  AC_DATACHANGE_LASTTIME00003
  ON  AUDIT_TABLE (DATACHANGE_LASTTIME ASC);

-- ----------------------------
-- Primary Key structure for table CLUSTER_TABLE
-- ----------------------------
ALTER TABLE  CLUSTER_TABLE ADD CONSTRAINT AC_PRIMARY00004 PRIMARY KEY (ID);

-- ----------------------------
-- Checks structure for table CLUSTER_TABLE
-- ----------------------------
ALTER TABLE  CLUSTER_TABLE ADD CONSTRAINT AC_SYS_C0028533 CHECK (ID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  CLUSTER_TABLE ADD CONSTRAINT AC_SYS_C0028534 CHECK (NAME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  CLUSTER_TABLE ADD CONSTRAINT AC_SYS_C0028535 CHECK (APPID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  CLUSTER_TABLE ADD CONSTRAINT AC_SYS_C0028536 CHECK (PARENTCLUSTERID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  CLUSTER_TABLE ADD CONSTRAINT AC_SYS_C0028537 CHECK (ISDELETED IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  CLUSTER_TABLE ADD CONSTRAINT AC_SYS_C0028538 CHECK (DATACHANGE_CREATEDTIME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table CLUSTER_TABLE
-- ----------------------------
CREATE INDEX  AC_DATACHANGE_LASTTIME00004
  ON  CLUSTER_TABLE (DATACHANGE_LASTTIME ASC);
CREATE INDEX  AC_IX_APPID_NAME
  ON  CLUSTER_TABLE (APPID ASC, NAME ASC);
CREATE INDEX  AC_IX_PARENTCLUSTERID
  ON  CLUSTER_TABLE (PARENTCLUSTERID ASC);

-- ----------------------------
-- Primary Key structure for table COMMIT
-- ----------------------------
ALTER TABLE  COMMIT ADD CONSTRAINT AC_PRIMARY00005 PRIMARY KEY (ID);

-- ----------------------------
-- Checks structure for table COMMIT
-- ----------------------------
ALTER TABLE  COMMIT ADD CONSTRAINT AC_SYS_C0028540 CHECK (ID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  COMMIT ADD CONSTRAINT AC_SYS_C0028541 CHECK (APPID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  COMMIT ADD CONSTRAINT AC_SYS_C0028542 CHECK (CLUSTERNAME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  COMMIT ADD CONSTRAINT AC_SYS_C0028543 CHECK (NAMESPACENAME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  COMMIT ADD CONSTRAINT AC_SYS_C0028544 CHECK (ISDELETED IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  COMMIT ADD CONSTRAINT AC_SYS_C0028545 CHECK (DATACHANGE_CREATEDTIME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table COMMIT
-- ----------------------------
CREATE INDEX  AC_APPID00005
  ON  COMMIT (APPID ASC);
CREATE INDEX  AC_CLUSTERNAME
  ON  COMMIT (CLUSTERNAME ASC);
CREATE INDEX  AC_DATACHANGE_LASTTIME00005
  ON  COMMIT (DATACHANGE_LASTTIME ASC);
CREATE INDEX  AC_NAMESPACENAME
  ON  COMMIT (NAMESPACENAME ASC);

-- ----------------------------
-- Primary Key structure for table GRAYRELEASERULE
-- ----------------------------
ALTER TABLE  GRAYRELEASERULE ADD CONSTRAINT AC_PRIMARY00006 PRIMARY KEY (ID);

-- ----------------------------
-- Checks structure for table GRAYRELEASERULE
-- ----------------------------
ALTER TABLE  GRAYRELEASERULE ADD CONSTRAINT AC_SYS_C0028547 CHECK (ID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  GRAYRELEASERULE ADD CONSTRAINT AC_SYS_C0028548 CHECK (APPID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  GRAYRELEASERULE ADD CONSTRAINT AC_SYS_C0028549 CHECK (CLUSTERNAME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  GRAYRELEASERULE ADD CONSTRAINT AC_SYS_C0028550 CHECK (NAMESPACENAME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  GRAYRELEASERULE ADD CONSTRAINT AC_SYS_C0028551 CHECK (BRANCHNAME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  GRAYRELEASERULE ADD CONSTRAINT AC_SYS_C0028552 CHECK (RELEASEID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  GRAYRELEASERULE ADD CONSTRAINT AC_SYS_C0028553 CHECK (ISDELETED IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  GRAYRELEASERULE ADD CONSTRAINT AC_SYS_C0028555 CHECK (DATACHANGE_CREATEDTIME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table GRAYRELEASERULE
-- ----------------------------
CREATE INDEX  AC_DATACHANGE_LASTTIME00006
  ON  GRAYRELEASERULE (DATACHANGE_LASTTIME ASC);
CREATE INDEX  AC_IX_NAMESPACE
  ON  GRAYRELEASERULE (CLUSTERNAME ASC, NAMESPACENAME ASC, APPID ASC);

-- ----------------------------
-- Primary Key structure for table INSTANCE
-- ----------------------------
ALTER TABLE  INSTANCE ADD CONSTRAINT PRIMARY00007 PRIMARY KEY (ID);

-- ----------------------------
-- Checks structure for table INSTANCE
-- ----------------------------
ALTER TABLE  INSTANCE ADD CONSTRAINT AC_SYS_C0028557 CHECK (ID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  INSTANCE ADD CONSTRAINT AC_SYS_C0028558 CHECK (APPID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  INSTANCE ADD CONSTRAINT AC_SYS_C0028559 CHECK (CLUSTERNAME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  INSTANCE ADD CONSTRAINT AC_SYS_C0028560 CHECK (IP IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  INSTANCE ADD CONSTRAINT AC_SYS_C0028561 CHECK (DATACHANGE_CREATEDTIME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  INSTANCE ADD CONSTRAINT AC_SYS_C0028562 CHECK (DATACHANGE_LASTTIME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table INSTANCE
-- ----------------------------
CREATE INDEX  AC_DATACHANGE_LASTTIME00007
  ON  INSTANCE (DATACHANGE_LASTTIME ASC);
CREATE INDEX  AC_IX_IP
  ON  INSTANCE (IP ASC);

-- ----------------------------
-- Primary Key structure for table INSTANCECONFIG
-- ----------------------------
ALTER TABLE  INSTANCECONFIG ADD CONSTRAINT AC_PRIMARY00008 PRIMARY KEY (ID);

-- ----------------------------
-- Checks structure for table INSTANCECONFIG
-- ----------------------------
ALTER TABLE  INSTANCECONFIG ADD CONSTRAINT AC_SYS_C0028564 CHECK (ID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  INSTANCECONFIG ADD CONSTRAINT AC_SYS_C0028565 CHECK (CONFIGAPPID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  INSTANCECONFIG ADD CONSTRAINT AC_SYS_C0028566 CHECK (CONFIGCLUSTERNAME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  INSTANCECONFIG ADD CONSTRAINT AC_SYS_C0028567 CHECK (CONFIGNAMESPACENAME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  INSTANCECONFIG ADD CONSTRAINT AC_SYS_C0028568 CHECK (RELEASEKEY IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  INSTANCECONFIG ADD CONSTRAINT AC_SYS_C0028569 CHECK (DATACHANGE_CREATEDTIME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  INSTANCECONFIG ADD CONSTRAINT AC_SYS_C0028570 CHECK (DATACHANGE_LASTTIME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table INSTANCECONFIG
-- ----------------------------
CREATE INDEX  AC_IX_DATACHANGE_LASTTIME00008
  ON  INSTANCECONFIG (DATACHANGE_LASTTIME ASC);
CREATE INDEX  AC_IX_RELEASEKEY
  ON  INSTANCECONFIG (RELEASEKEY ASC);
CREATE INDEX  AC_IX_VALID_NAMESPACE
  ON  INSTANCECONFIG (CONFIGNAMESPACENAME ASC, CONFIGCLUSTERNAME ASC, DATACHANGE_LASTTIME ASC, CONFIGAPPID ASC);

-- ----------------------------
-- Primary Key structure for table ITEM
-- ----------------------------
ALTER TABLE  ITEM ADD CONSTRAINT AC_PRIMARY00009 PRIMARY KEY (ID);

-- ----------------------------
-- Checks structure for table ITEM
-- ----------------------------
ALTER TABLE  ITEM ADD CONSTRAINT AC_SYS_C0028572 CHECK (ID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  ITEM ADD CONSTRAINT AC_SYS_C0028573 CHECK (NAMESPACEID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  ITEM ADD CONSTRAINT AC_SYS_C0028574 CHECK (KEY_COL IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  ITEM ADD CONSTRAINT AC_SYS_C0028575 CHECK (ISDELETED IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  ITEM ADD CONSTRAINT AC_SYS_C0028576 CHECK (DATACHANGE_CREATEDTIME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table ITEM
-- ----------------------------
CREATE INDEX  AC_DATACHANGE_LASTTIME00009
  ON  ITEM (DATACHANGE_LASTTIME ASC);
CREATE INDEX  AC_IX_GROUPID
  ON  ITEM (NAMESPACEID ASC);

-- ----------------------------
-- Primary Key structure for table NAMESPACE
-- ----------------------------
ALTER TABLE  NAMESPACE ADD CONSTRAINT AC_PRIMARY00010 PRIMARY KEY (ID);

-- ----------------------------
-- Checks structure for table NAMESPACE
-- ----------------------------
ALTER TABLE  NAMESPACE ADD CONSTRAINT AC_SYS_C0028578 CHECK (ID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  NAMESPACE ADD CONSTRAINT AC_SYS_C0028579 CHECK (APPID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  NAMESPACE ADD CONSTRAINT AC_SYS_C0028580 CHECK (CLUSTERNAME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  NAMESPACE ADD CONSTRAINT AC_SYS_C0028581 CHECK (NAMESPACENAME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  NAMESPACE ADD CONSTRAINT AC_SYS_C0028582 CHECK (ISDELETED IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  NAMESPACE ADD CONSTRAINT AC_SYS_C0028583 CHECK (DATACHANGE_CREATEDTIME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  NAMESPACE ADD CONSTRAINT AC_SYS_C0028724 CHECK (DATACHANGE_CREATEDBY IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table NAMESPACE
-- ----------------------------
CREATE INDEX  AC_CLUSTERNAME_NAMESPACENA
  ON  NAMESPACE (APPID ASC, CLUSTERNAME ASC, NAMESPACENAME ASC);
CREATE INDEX  AC_DATACHANGE_LASTTIME00010
  ON  NAMESPACE (DATACHANGE_LASTTIME ASC);
CREATE INDEX  AC_IX_NAMESPACENAME
  ON  NAMESPACE (NAMESPACENAME ASC);

-- ----------------------------
-- Primary Key structure for table NAMESPACELOCK
-- ----------------------------
ALTER TABLE  NAMESPACELOCK ADD CONSTRAINT AC_PRIMARY00011 PRIMARY KEY (ID);

-- ----------------------------
-- Checks structure for table NAMESPACELOCK
-- ----------------------------
ALTER TABLE  NAMESPACELOCK ADD CONSTRAINT AC_SYS_C0028585 CHECK (ID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  NAMESPACELOCK ADD CONSTRAINT AC_SYS_C0028586 CHECK (NAMESPACEID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  NAMESPACELOCK ADD CONSTRAINT AC_SYS_C0028587 CHECK (ISDELETED IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  NAMESPACELOCK ADD CONSTRAINT AC_SYS_C0028588 CHECK (DATACHANGE_CREATEDTIME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table NAMESPACELOCK
-- ----------------------------
CREATE INDEX  AC_DATACHANGE_LASTTIME00011
  ON  NAMESPACELOCK (DATACHANGE_LASTTIME ASC);

-- ----------------------------
-- Primary Key structure for table RELEASEHISTORY
-- ----------------------------
ALTER TABLE  RELEASEHISTORY ADD CONSTRAINT AC_PRIMARY00014 PRIMARY KEY (ID);

-- ----------------------------
-- Checks structure for table RELEASEHISTORY
-- ----------------------------
ALTER TABLE  RELEASEHISTORY ADD CONSTRAINT AC_SYS_C0028604 CHECK (ID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  RELEASEHISTORY ADD CONSTRAINT AC_SYS_C0028605 CHECK (APPID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  RELEASEHISTORY ADD CONSTRAINT AC_SYS_C0028606 CHECK (CLUSTERNAME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  RELEASEHISTORY ADD CONSTRAINT AC_SYS_C0028607 CHECK (NAMESPACENAME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  RELEASEHISTORY ADD CONSTRAINT AC_SYS_C0028608 CHECK (BRANCHNAME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  RELEASEHISTORY ADD CONSTRAINT AC_SYS_C0028609 CHECK (RELEASEID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  RELEASEHISTORY ADD CONSTRAINT AC_SYS_C0028610 CHECK (PREVIOUSRELEASEID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  RELEASEHISTORY ADD CONSTRAINT AC_SYS_C0028611 CHECK (OPERATION IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  RELEASEHISTORY ADD CONSTRAINT AC_SYS_C0028612 CHECK (ISDELETED IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  RELEASEHISTORY ADD CONSTRAINT AC_SYS_C0028613 CHECK (DATACHANGE_CREATEDTIME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table RELEASEHISTORY
-- ----------------------------
CREATE INDEX  AC_DATACHANGE_LASTTIME00014
  ON  RELEASEHISTORY (DATACHANGE_LASTTIME ASC);
CREATE INDEX  AC_IX_NAMESPACE00014
  ON  RELEASEHISTORY (APPID ASC, CLUSTERNAME ASC, NAMESPACENAME ASC, BRANCHNAME ASC);
CREATE INDEX  AC_IX_RELEASEID
  ON  RELEASEHISTORY (RELEASEID ASC);

-- ----------------------------
-- Primary Key structure for table RELEASEMESSAGE
-- ----------------------------
ALTER TABLE  RELEASEMESSAGE ADD CONSTRAINT AC_PRIMARY00013 PRIMARY KEY (ID);

-- ----------------------------
-- Checks structure for table RELEASEMESSAGE
-- ----------------------------
ALTER TABLE  RELEASEMESSAGE ADD CONSTRAINT AC_SYS_C0028600 CHECK (ID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  RELEASEMESSAGE ADD CONSTRAINT AC_SYS_C0028601 CHECK (MESSAGE IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  RELEASEMESSAGE ADD CONSTRAINT AC_SYS_C0028602 CHECK (DATACHANGE_LASTTIME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table RELEASEMESSAGE
-- ----------------------------
CREATE INDEX  AC_DATACHANGE_LASTTIME00013
  ON  RELEASEMESSAGE (DATACHANGE_LASTTIME ASC);
CREATE INDEX  AC_IX_MESSAGE
  ON  RELEASEMESSAGE (MESSAGE ASC);

-- ----------------------------
-- Primary Key structure for table RELEASE_TABLE
-- ----------------------------
ALTER TABLE  RELEASE_TABLE ADD CONSTRAINT AC_PRIMARY00012 PRIMARY KEY (ID);

-- ----------------------------
-- Checks structure for table RELEASE_TABLE
-- ----------------------------
ALTER TABLE  RELEASE_TABLE ADD CONSTRAINT AC_SYS_C0028590 CHECK (ID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  RELEASE_TABLE ADD CONSTRAINT AC_SYS_C0028591 CHECK (RELEASEKEY IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  RELEASE_TABLE ADD CONSTRAINT AC_SYS_C0028592 CHECK (NAME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  RELEASE_TABLE ADD CONSTRAINT AC_SYS_C0028593 CHECK (APPID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  RELEASE_TABLE ADD CONSTRAINT AC_SYS_C0028594 CHECK (CLUSTERNAME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  RELEASE_TABLE ADD CONSTRAINT AC_SYS_C0028595 CHECK (NAMESPACENAME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  RELEASE_TABLE ADD CONSTRAINT AC_SYS_C0028596 CHECK (ISABANDONED IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  RELEASE_TABLE ADD CONSTRAINT AC_SYS_C0028597 CHECK (ISDELETED IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  RELEASE_TABLE ADD CONSTRAINT AC_SYS_C0028598 CHECK (DATACHANGE_CREATEDTIME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table RELEASE_TABLE
-- ----------------------------
CREATE INDEX  AC_CLUSTERNAME_GROUPNAME
  ON  RELEASE_TABLE (APPID ASC, CLUSTERNAME ASC, NAMESPACENAME ASC);
CREATE INDEX  AC_DATACHANGE_LASTTIME00012
  ON  RELEASE_TABLE (DATACHANGE_LASTTIME ASC);
CREATE INDEX  AC_IX_RELEASEKEY00012
  ON  RELEASE_TABLE (RELEASEKEY ASC);

-- ----------------------------
-- Primary Key structure for table SERVERCONFIG
-- ----------------------------
ALTER TABLE  SERVERCONFIG ADD CONSTRAINT AC_PRIMARY00015 PRIMARY KEY (ID);

-- ----------------------------
-- Checks structure for table SERVERCONFIG
-- ----------------------------
ALTER TABLE  SERVERCONFIG ADD CONSTRAINT AC_SYS_C0028615 CHECK (ID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  SERVERCONFIG ADD CONSTRAINT AC_SYS_C0028616 CHECK (KEY_COL IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  SERVERCONFIG ADD CONSTRAINT AC_SYS_C0028617 CHECK (CLUSTER_COL IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  SERVERCONFIG ADD CONSTRAINT AC_SYS_C0028618 CHECK (ISDELETED IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  SERVERCONFIG ADD CONSTRAINT AC_SYS_C0028619 CHECK (DATACHANGE_CREATEDTIME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table SERVERCONFIG
-- ----------------------------
CREATE INDEX  AC_DATACHANGE_LASTTIME00015
  ON  SERVERCONFIG (DATACHANGE_LASTTIME ASC);
CREATE INDEX  AC_IX_KEY
  ON  SERVERCONFIG (KEY_COL ASC);

-- ----------------------------
-- Checks structure for table SYS_ID_MACHINE
-- ----------------------------
ALTER TABLE  SYS_ID_MACHINE ADD CONSTRAINT AC_SYS_C0026687 CHECK (MACHINE_IP IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  SYS_ID_MACHINE ADD CONSTRAINT AC_SYS_C0026688 CHECK (MACHINE_ID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  SYS_ID_MACHINE ADD CONSTRAINT AC_SYS_C0026689 CHECK (ADD_TIME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  SYS_ID_MACHINE ADD CONSTRAINT AC_SYS_C0026690 CHECK (HEART_LAST_TIME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  SYS_ID_MACHINE ADD CONSTRAINT AC_SYS_C0028622 CHECK (MACHINE_IP IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  SYS_ID_MACHINE ADD CONSTRAINT AC_SYS_C0028623 CHECK (MACHINE_ID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  SYS_ID_MACHINE ADD CONSTRAINT AC_SYS_C0028624 CHECK (ADD_TIME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  SYS_ID_MACHINE ADD CONSTRAINT AC_SYS_C0028625 CHECK (HEART_LAST_TIME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  SYS_ID_MACHINE ADD CONSTRAINT AC_SYS_C0028706 CHECK (MACHINE_IP IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  SYS_ID_MACHINE ADD CONSTRAINT AC_SYS_C0028707 CHECK (MACHINE_ID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  SYS_ID_MACHINE ADD CONSTRAINT AC_SYS_C0028708 CHECK (ADD_TIME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE  SYS_ID_MACHINE ADD CONSTRAINT AC_SYS_C0028709 CHECK (HEART_LAST_TIME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table SYS_ID_MACHINE
-- ----------------------------
CREATE UNIQUE INDEX  AC_SYS_MACHINE_INDEX_IP
  ON  SYS_ID_MACHINE (MACHINE_IP ASC);
