spring:
  application:
    name: apollo-adminservice
  profiles:
    active: ${apollo_profile}

  datasource:
    url: jdbc:mysql://192.168.1.116:3306/apolloconfigdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root@123
    driver-class-name: com.mysql.jdbc.Driver
    validation-query: select 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

ctrip:
  appid: 100003172
  
server:
  port: 8090
  
logging:
  file: /opt/logs/100003172/apollo-adminservice.log

