/*
 Navicat Premium Data Transfer

 Source Server         : 192.168.1.99
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : 192.168.1.99:1521
 Source Schema         : APOLLOCONFIGDB

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 30/07/2020 19:51:07
*/


-- ----------------------------
-- Table structure for ACCESSKEY
-- ----------------------------
CREATE TABLE "APOLLOCONFIGDB"."ACCESSKEY" (
  "ID" NUMBER NOT NULL ,
  "APPID" NVARCHAR2(500) DEFAULT 'default'  NOT NULL ,
  "SECRET" VARCHAR2(128 BYTE) DEFAULT 'default'  NOT NULL ,
  "ISENABLED" NUMBER(3) DEFAULT 0  NOT NULL ,
  "ISDELETED" NUMBER(3) DEFAULT 0  NOT NULL ,
  "DATACHANGE_CREATEDBY" VARCHAR2(32 BYTE) ,
  "DATACHANGE_CREATEDTIME" DATE NOT NULL ,
  "DATACHANGE_LASTMODIFIEDBY" VARCHAR2(32 BYTE) ,
  "DATACHANGE_LASTTIME" DATE 
)
TABLESPACE "APOLLOCONFIGDB"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."ACCESSKEY"."ID" IS '主键ID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ACCESSKEY"."APPID" IS 'APPID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ACCESSKEY"."SECRET" IS 'Secret';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ACCESSKEY"."ISENABLED" IS '启用标志：1: enabled, 0: disabled';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ACCESSKEY"."ISDELETED" IS '删除标志：1: deleted, 0: normal';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ACCESSKEY"."DATACHANGE_CREATEDBY" IS '创建人';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ACCESSKEY"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ACCESSKEY"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ACCESSKEY"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."ACCESSKEY" IS '访问密钥';

-- ----------------------------
-- Table structure for APP
-- ----------------------------
CREATE TABLE "APOLLOCONFIGDB"."APP" (
  "ID" NUMBER NOT NULL ,
  "APPID" VARCHAR2(500 BYTE) DEFAULT 'default'  NOT NULL ,
  "NAME" VARCHAR2(500 BYTE) DEFAULT 'default'  NOT NULL ,
  "ORGID" VARCHAR2(32 BYTE) DEFAULT 'default'  NOT NULL ,
  "ORGNAME" VARCHAR2(64 BYTE) DEFAULT 'default'  NOT NULL ,
  "OWNERNAME" VARCHAR2(500 BYTE) DEFAULT 'default'  NOT NULL ,
  "OWNEREMAIL" VARCHAR2(500 BYTE) DEFAULT 'default'  NOT NULL ,
  "ISDELETED" NUMBER(3) DEFAULT 0  NOT NULL ,
  "DATACHANGE_CREATEDBY" VARCHAR2(32 BYTE) ,
  "DATACHANGE_CREATEDTIME" DATE NOT NULL ,
  "DATACHANGE_LASTMODIFIEDBY" VARCHAR2(32 BYTE) ,
  "DATACHANGE_LASTTIME" DATE 
)
TABLESPACE "APOLLOCONFIGDB"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."APP"."ID" IS '主键';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APP"."APPID" IS 'APPID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APP"."NAME" IS '应用名';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APP"."ORGID" IS '部门Id';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APP"."ORGNAME" IS '部门名字';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APP"."OWNERNAME" IS 'ownerName';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APP"."OWNEREMAIL" IS 'ownerEmail';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APP"."ISDELETED" IS '删除标志：1: deleted, 0: normal';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APP"."DATACHANGE_CREATEDBY" IS '创建人';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APP"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APP"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APP"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."APP" IS '应用表';

-- ----------------------------
-- Records of "APP"
-- ----------------------------
INSERT INTO "APOLLOCONFIGDB"."APP" VALUES ('1', 'SampleApp', 'Sample App', 'TEST1', '样例部门1', 'apollo', 'apollo@acme.com', '0', 'default', TO_DATE('2017-09-11 15:41:26', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2017-09-11 15:41:26', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for APPNAMESPACE
-- ----------------------------
CREATE TABLE "APOLLOCONFIGDB"."APPNAMESPACE" (
  "ID" NUMBER NOT NULL ,
  "NAME" VARCHAR2(32 BYTE) NOT NULL ,
  "APPID" VARCHAR2(32 BYTE) NOT NULL ,
  "FORMAT" VARCHAR2(32 BYTE) DEFAULT 'properties'  NOT NULL ,
  "ISPUBLIC" NUMBER(3) DEFAULT 0  NOT NULL ,
  "COMMT" VARCHAR2(64 BYTE) ,
  "ISDELETED" NUMBER(3) DEFAULT 0  NOT NULL ,
  "DATACHANGE_CREATEDBY" VARCHAR2(32 BYTE) ,
  "DATACHANGE_CREATEDTIME" DATE NOT NULL ,
  "DATACHANGE_LASTMODIFIEDBY" VARCHAR2(32 BYTE) ,
  "DATACHANGE_LASTTIME" DATE 
)
TABLESPACE "APOLLOCONFIGDB"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."APPNAMESPACE"."ID" IS '主键';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APPNAMESPACE"."NAME" IS 'namespace名字，注意，需要全局唯一';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APPNAMESPACE"."APPID" IS 'APPID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APPNAMESPACE"."FORMAT" IS 'namespace的format类型';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APPNAMESPACE"."ISPUBLIC" IS 'namespace是否为公共';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APPNAMESPACE"."COMMT" IS '注释';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APPNAMESPACE"."ISDELETED" IS '删除标志：1: deleted, 0: normal';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APPNAMESPACE"."DATACHANGE_CREATEDBY" IS '创建人';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APPNAMESPACE"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APPNAMESPACE"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人';
COMMENT ON COLUMN "APOLLOCONFIGDB"."APPNAMESPACE"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."APPNAMESPACE" IS '应用命名空间';

-- ----------------------------
-- Records of "APPNAMESPACE"
-- ----------------------------
INSERT INTO "APOLLOCONFIGDB"."APPNAMESPACE" VALUES ('1', 'application', 'SampleApp', 'properties', '0', 'default app namespace', '0', NULL, TO_DATE('2017-09-11 15:41:27', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2017-09-11 15:41:27', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for AUDIT_TABLE
-- ----------------------------
CREATE TABLE "APOLLOCONFIGDB"."AUDIT_TABLE" (
  "ID" NUMBER NOT NULL ,
  "ENTITYNAME" VARCHAR2(50 BYTE) DEFAULT 'default'  NOT NULL ,
  "ENTITYID" NUMBER ,
  "OPNAME" VARCHAR2(50 BYTE) DEFAULT 'default'  NOT NULL ,
  "COMMT" VARCHAR2(500 BYTE) ,
  "ISDELETED" NUMBER(3) DEFAULT 0  NOT NULL ,
  "DATACHANGE_CREATEDBY" VARCHAR2(32 BYTE) ,
  "DATACHANGE_CREATEDTIME" DATE NOT NULL ,
  "DATACHANGE_LASTMODIFIEDBY" VARCHAR2(32 BYTE) ,
  "DATACHANGE_LASTTIME" DATE 
)
TABLESPACE "APOLLOCONFIGDB"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."AUDIT_TABLE"."ID" IS '主键';
COMMENT ON COLUMN "APOLLOCONFIGDB"."AUDIT_TABLE"."ENTITYNAME" IS '表名';
COMMENT ON COLUMN "APOLLOCONFIGDB"."AUDIT_TABLE"."ENTITYID" IS '记录ID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."AUDIT_TABLE"."OPNAME" IS '操作类型';
COMMENT ON COLUMN "APOLLOCONFIGDB"."AUDIT_TABLE"."COMMT" IS '备注';
COMMENT ON COLUMN "APOLLOCONFIGDB"."AUDIT_TABLE"."ISDELETED" IS '删除标志：1: deleted, 0: normal';
COMMENT ON COLUMN "APOLLOCONFIGDB"."AUDIT_TABLE"."DATACHANGE_CREATEDBY" IS '创建人';
COMMENT ON COLUMN "APOLLOCONFIGDB"."AUDIT_TABLE"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."AUDIT_TABLE"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人';
COMMENT ON COLUMN "APOLLOCONFIGDB"."AUDIT_TABLE"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."AUDIT_TABLE" IS '日志审计表';

-- ----------------------------
-- Table structure for CLUSTER_TABLE
-- ----------------------------
CREATE TABLE "APOLLOCONFIGDB"."CLUSTER_TABLE" (
  "ID" NUMBER NOT NULL ,
  "NAME" VARCHAR2(32 BYTE) NOT NULL ,
  "APPID" VARCHAR2(32 BYTE) NOT NULL ,
  "PARENTCLUSTERID" NUMBER DEFAULT 0  NOT NULL ,
  "ISDELETED" NUMBER(3) DEFAULT 0  NOT NULL ,
  "DATACHANGE_CREATEDBY" VARCHAR2(32 BYTE) ,
  "DATACHANGE_CREATEDTIME" DATE NOT NULL ,
  "DATACHANGE_LASTMODIFIEDBY" VARCHAR2(32 BYTE) ,
  "DATACHANGE_LASTTIME" DATE 
)
TABLESPACE "APOLLOCONFIGDB"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."CLUSTER_TABLE"."ID" IS '主键';
COMMENT ON COLUMN "APOLLOCONFIGDB"."CLUSTER_TABLE"."NAME" IS '集群名字';
COMMENT ON COLUMN "APOLLOCONFIGDB"."CLUSTER_TABLE"."APPID" IS 'APPID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."CLUSTER_TABLE"."PARENTCLUSTERID" IS '父cluster';
COMMENT ON COLUMN "APOLLOCONFIGDB"."CLUSTER_TABLE"."ISDELETED" IS '删除标志：1: deleted, 0: normal';
COMMENT ON COLUMN "APOLLOCONFIGDB"."CLUSTER_TABLE"."DATACHANGE_CREATEDBY" IS '创建人';
COMMENT ON COLUMN "APOLLOCONFIGDB"."CLUSTER_TABLE"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."CLUSTER_TABLE"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人';
COMMENT ON COLUMN "APOLLOCONFIGDB"."CLUSTER_TABLE"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."CLUSTER_TABLE" IS '集群';

-- ----------------------------
-- Records of "CLUSTER_TABLE"
-- ----------------------------
INSERT INTO "APOLLOCONFIGDB"."CLUSTER_TABLE" VALUES ('1', 'default', 'SampleApp', '0', '0', NULL, TO_DATE('2017-09-11 15:41:27', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2017-09-11 15:41:27', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for COMMIT
-- ----------------------------
CREATE TABLE "APOLLOCONFIGDB"."COMMIT" (
  "ID" NUMBER NOT NULL ,
  "CHANGESETS" CLOB ,
  "APPID" VARCHAR2(500 BYTE) DEFAULT 'default'  NOT NULL ,
  "CLUSTERNAME" VARCHAR2(500 BYTE) DEFAULT 'default'  NOT NULL ,
  "NAMESPACENAME" VARCHAR2(500 BYTE) DEFAULT 'default'  NOT NULL ,
  "COMMT" VARCHAR2(500 BYTE) ,
  "ISDELETED" NUMBER(3) DEFAULT 0  NOT NULL ,
  "DATACHANGE_CREATEDBY" VARCHAR2(32 BYTE) ,
  "DATACHANGE_CREATEDTIME" DATE NOT NULL ,
  "DATACHANGE_LASTMODIFIEDBY" VARCHAR2(32 BYTE) ,
  "DATACHANGE_LASTTIME" DATE 
)
TABLESPACE "APOLLOCONFIGDB"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."COMMIT"."ID" IS '主键';
COMMENT ON COLUMN "APOLLOCONFIGDB"."COMMIT"."CHANGESETS" IS '修改变更集';
COMMENT ON COLUMN "APOLLOCONFIGDB"."COMMIT"."APPID" IS 'APPID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."COMMIT"."CLUSTERNAME" IS 'ClusterName';
COMMENT ON COLUMN "APOLLOCONFIGDB"."COMMIT"."NAMESPACENAME" IS 'namespaceName';
COMMENT ON COLUMN "APOLLOCONFIGDB"."COMMIT"."COMMT" IS '备注';
COMMENT ON COLUMN "APOLLOCONFIGDB"."COMMIT"."ISDELETED" IS '删除标志：1: deleted, 0: normal';
COMMENT ON COLUMN "APOLLOCONFIGDB"."COMMIT"."DATACHANGE_CREATEDBY" IS '创建人';
COMMENT ON COLUMN "APOLLOCONFIGDB"."COMMIT"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."COMMIT"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人';
COMMENT ON COLUMN "APOLLOCONFIGDB"."COMMIT"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."COMMIT" IS 'commit历史表';

-- ----------------------------
-- Table structure for GRAYRELEASERULE
-- ----------------------------
CREATE TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" (
  "ID" NUMBER NOT NULL ,
  "APPID" VARCHAR2(32 BYTE) DEFAULT 'default'  NOT NULL ,
  "CLUSTERNAME" VARCHAR2(32 BYTE) DEFAULT 'default'  NOT NULL ,
  "NAMESPACENAME" VARCHAR2(32 BYTE) DEFAULT 'default'  NOT NULL ,
  "BRANCHNAME" VARCHAR2(32 BYTE) DEFAULT 'default'  NOT NULL ,
  "RULES" VARCHAR2(1600 BYTE) DEFAULT '[]' ,
  "RELEASEID" NUMBER DEFAULT 0  NOT NULL ,
  "BRANCHSTATUS" NUMBER(3) DEFAULT 1 ,
  "ISDELETED" NUMBER(3) DEFAULT 0  NOT NULL ,
  "DATACHANGE_CREATEDBY" VARCHAR2(32 BYTE) DEFAULT 'default'  ,
  "DATACHANGE_CREATEDTIME" DATE NOT NULL ,
  "DATACHANGE_LASTMODIFIEDBY" VARCHAR2(32 BYTE) ,
  "DATACHANGE_LASTTIME" DATE 
)
TABLESPACE "APOLLOCONFIGDB"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."GRAYRELEASERULE"."ID" IS '主键';
COMMENT ON COLUMN "APOLLOCONFIGDB"."GRAYRELEASERULE"."APPID" IS 'AppID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."GRAYRELEASERULE"."CLUSTERNAME" IS 'Cluster Name';
COMMENT ON COLUMN "APOLLOCONFIGDB"."GRAYRELEASERULE"."NAMESPACENAME" IS 'Namespace Name';
COMMENT ON COLUMN "APOLLOCONFIGDB"."GRAYRELEASERULE"."BRANCHNAME" IS 'branch name';
COMMENT ON COLUMN "APOLLOCONFIGDB"."GRAYRELEASERULE"."RULES" IS '灰度规则';
COMMENT ON COLUMN "APOLLOCONFIGDB"."GRAYRELEASERULE"."RELEASEID" IS '灰度对应的release';
COMMENT ON COLUMN "APOLLOCONFIGDB"."GRAYRELEASERULE"."BRANCHSTATUS" IS '灰度分支状态: 0:删除分支,1:正在使用的规则 2：全量发布';
COMMENT ON COLUMN "APOLLOCONFIGDB"."GRAYRELEASERULE"."ISDELETED" IS '删除标志：1: deleted, 0: normal';
COMMENT ON COLUMN "APOLLOCONFIGDB"."GRAYRELEASERULE"."DATACHANGE_CREATEDBY" IS '创建人';
COMMENT ON COLUMN "APOLLOCONFIGDB"."GRAYRELEASERULE"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."GRAYRELEASERULE"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人';
COMMENT ON COLUMN "APOLLOCONFIGDB"."GRAYRELEASERULE"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" IS '灰度规则表';

-- ----------------------------
-- Table structure for INSTANCE
-- ----------------------------
CREATE TABLE "APOLLOCONFIGDB"."INSTANCE" (
  "ID" NUMBER NOT NULL ,
  "APPID" VARCHAR2(32 BYTE) DEFAULT 'default'  NOT NULL ,
  "CLUSTERNAME" VARCHAR2(32 BYTE) DEFAULT 'default'  NOT NULL ,
  "DATACENTER" VARCHAR2(64 BYTE) DEFAULT 'default' ,
  "IP" VARCHAR2(32 BYTE) NOT NULL ,
  "DATACHANGE_CREATEDTIME" DATE NOT NULL ,
  "DATACHANGE_LASTTIME" DATE NOT NULL 
)
TABLESPACE "APOLLOCONFIGDB"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCE"."ID" IS '主键';
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCE"."APPID" IS 'AppID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCE"."CLUSTERNAME" IS 'Cluster Name';
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCE"."DATACENTER" IS 'Data Center Name';
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCE"."IP" IS 'instance ip';
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCE"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCE"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."INSTANCE" IS '使用配置的应用实例';

-- ----------------------------
-- Table structure for INSTANCECONFIG
-- ----------------------------
CREATE TABLE "APOLLOCONFIGDB"."INSTANCECONFIG" (
  "ID" NUMBER NOT NULL ,
  "INSTANCEID" NUMBER ,
  "CONFIGAPPID" VARCHAR2(32 BYTE) DEFAULT 'default'  NOT NULL ,
  "CONFIGCLUSTERNAME" VARCHAR2(32 BYTE) DEFAULT 'default'  NOT NULL ,
  "CONFIGNAMESPACENAME" VARCHAR2(32 BYTE) DEFAULT 'default'  NOT NULL ,
  "RELEASEKEY" VARCHAR2(64 BYTE) NOT NULL ,
  "RELEASEDELIVERYTIME" DATE ,
  "DATACHANGE_CREATEDTIME" DATE NOT NULL ,
  "DATACHANGE_LASTTIME" DATE NOT NULL 
)
TABLESPACE "APOLLOCONFIGDB"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCECONFIG"."ID" IS '主键';
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCECONFIG"."INSTANCEID" IS 'Instance Id';
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCECONFIG"."CONFIGAPPID" IS 'Config App Id';
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCECONFIG"."CONFIGCLUSTERNAME" IS 'Config Cluster Name';
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCECONFIG"."CONFIGNAMESPACENAME" IS 'Config Namespace Name';
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCECONFIG"."RELEASEKEY" IS '发布的Key';
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCECONFIG"."RELEASEDELIVERYTIME" IS '配置获取时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCECONFIG"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."INSTANCECONFIG"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."INSTANCECONFIG" IS '应用实例的配置信息';

-- ----------------------------
-- Table structure for ITEM
-- ----------------------------
CREATE TABLE "APOLLOCONFIGDB"."ITEM" (
  "ID" NUMBER NOT NULL ,
  "NAMESPACEID" NUMBER DEFAULT 0  NOT NULL ,
  "KEY_COL" VARCHAR2(128 BYTE) DEFAULT 'default'  NOT NULL ,
  "VALUE_COL" CLOB ,
  "COMMT" VARCHAR2(1024 BYTE) ,
  "LINENUM" NUMBER DEFAULT 0 ,
  "ISDELETED" NUMBER(3) DEFAULT 0  NOT NULL ,
  "DATACHANGE_CREATEDBY" VARCHAR2(32 BYTE) ,
  "DATACHANGE_CREATEDTIME" DATE NOT NULL ,
  "DATACHANGE_LASTMODIFIEDBY" VARCHAR2(32 BYTE) ,
  "DATACHANGE_LASTTIME" DATE 
)
TABLESPACE "APOLLOCONFIGDB"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."ITEM"."ID" IS '主键';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ITEM"."NAMESPACEID" IS '集群NamespaceId';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ITEM"."KEY_COL" IS '配置项Key';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ITEM"."VALUE_COL" IS '配置项值';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ITEM"."COMMT" IS '注释';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ITEM"."LINENUM" IS '行号';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ITEM"."ISDELETED" IS '删除标志：1: deleted, 0: normal';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ITEM"."DATACHANGE_CREATEDBY" IS '创建人';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ITEM"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ITEM"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人';
COMMENT ON COLUMN "APOLLOCONFIGDB"."ITEM"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."ITEM" IS '配置项目';

-- ----------------------------
-- Records of "ITEM"
-- ----------------------------
INSERT INTO "APOLLOCONFIGDB"."ITEM" VALUES ('1', '1', 'timeout', '100', 'sample timeout配置', '1', '0', 'default', TO_DATE('2017-09-11 15:41:27', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2017-09-11 15:41:27', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for NAMESPACE
-- ----------------------------
CREATE TABLE "APOLLOCONFIGDB"."NAMESPACE" (
  "ID" NUMBER NOT NULL ,
  "APPID" VARCHAR2(500 BYTE) DEFAULT 'default'  NOT NULL ,
  "CLUSTERNAME" VARCHAR2(500 BYTE) DEFAULT 'default'  NOT NULL ,
  "NAMESPACENAME" VARCHAR2(500 BYTE) DEFAULT 'default'  NOT NULL ,
  "ISDELETED" NUMBER(3) DEFAULT 0  NOT NULL ,
  "DATACHANGE_CREATEDBY" VARCHAR2(32 BYTE) NOT NULL ,
  "DATACHANGE_CREATEDTIME" DATE NOT NULL ,
  "DATACHANGE_LASTMODIFIEDBY" VARCHAR2(32 BYTE) ,
  "DATACHANGE_LASTTIME" DATE 
)
TABLESPACE "APOLLOCONFIGDB"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACE"."ID" IS '主键';
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACE"."APPID" IS 'AppID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACE"."CLUSTERNAME" IS 'Cluster Name';
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACE"."NAMESPACENAME" IS 'Namespace Name';
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACE"."ISDELETED" IS '删除标志：1: deleted, 0: normal';
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACE"."DATACHANGE_CREATEDBY" IS '创建人';
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACE"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACE"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人';
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACE"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."NAMESPACE" IS '命名空间';

-- ----------------------------
-- Records of "NAMESPACE"
-- ----------------------------
INSERT INTO "APOLLOCONFIGDB"."NAMESPACE" VALUES ('1', 'SampleApp', 'default', 'application', '0', 'default', TO_DATE('2017-09-11 15:41:27', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2017-09-11 15:41:27', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for NAMESPACELOCK
-- ----------------------------
CREATE TABLE "APOLLOCONFIGDB"."NAMESPACELOCK" (
  "ID" NUMBER NOT NULL ,
  "NAMESPACEID" NUMBER DEFAULT 0  NOT NULL ,
  "ISDELETED" NUMBER(3) DEFAULT 0  NOT NULL ,
  "DATACHANGE_CREATEDBY" VARCHAR2(32 BYTE) ,
  "DATACHANGE_CREATEDTIME" DATE NOT NULL ,
  "DATACHANGE_LASTMODIFIEDBY" VARCHAR2(32 BYTE) ,
  "DATACHANGE_LASTTIME" DATE 
)
TABLESPACE "APOLLOCONFIGDB"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACELOCK"."ID" IS '主键';
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACELOCK"."NAMESPACEID" IS '集群NamespaceId';
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACELOCK"."ISDELETED" IS '删除标志：1: deleted, 0: normal';
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACELOCK"."DATACHANGE_CREATEDBY" IS '创建人';
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACELOCK"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACELOCK"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人';
COMMENT ON COLUMN "APOLLOCONFIGDB"."NAMESPACELOCK"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."NAMESPACELOCK" IS '命名空间编辑锁';

-- ----------------------------
-- Table structure for RELEASEHISTORY
-- ----------------------------
CREATE TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" (
  "ID" NUMBER NOT NULL ,
  "APPID" VARCHAR2(32 BYTE) DEFAULT 'default'  NOT NULL ,
  "CLUSTERNAME" VARCHAR2(32 BYTE) DEFAULT 'default'  NOT NULL ,
  "NAMESPACENAME" VARCHAR2(32 BYTE) DEFAULT 'default'  NOT NULL ,
  "BRANCHNAME" VARCHAR2(32 BYTE) DEFAULT 'default'  NOT NULL ,
  "RELEASEID" NUMBER DEFAULT 0  NOT NULL ,
  "PREVIOUSRELEASEID" NUMBER DEFAULT 0  NOT NULL ,
  "OPERATION" NUMBER(5) DEFAULT 0  NOT NULL ,
  "OPERATIONCONTEXT" CLOB ,
  "ISDELETED" NUMBER(3) DEFAULT 0  NOT NULL ,
  "DATACHANGE_CREATEDBY" VARCHAR2(32 BYTE) ,
  "DATACHANGE_CREATEDTIME" DATE NOT NULL ,
  "DATACHANGE_LASTMODIFIEDBY" VARCHAR2(32 BYTE) ,
  "DATACHANGE_LASTTIME" DATE 
)
TABLESPACE "APOLLOCONFIGDB"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEHISTORY"."ID" IS '主键';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEHISTORY"."APPID" IS 'AppID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEHISTORY"."CLUSTERNAME" IS 'ClusterName';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEHISTORY"."NAMESPACENAME" IS 'namespaceName';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEHISTORY"."BRANCHNAME" IS '发布分支名';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEHISTORY"."RELEASEID" IS '关联的Release Id';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEHISTORY"."PREVIOUSRELEASEID" IS '前一次发布的ReleaseId';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEHISTORY"."OPERATION" IS '发布类型，0: 普通发布，1: 回滚，2: 灰度发布，3: 灰度规则更新，4: 灰度合并回主分支发布，5: 主分支发布灰度自动发布，6: 主分支回滚灰度自动发布，7: 放弃灰度';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEHISTORY"."OPERATIONCONTEXT" IS '发布上下文信息';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEHISTORY"."ISDELETED" IS '删除标志：1: deleted, 0: normal';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEHISTORY"."DATACHANGE_CREATEDBY" IS '创建人';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEHISTORY"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEHISTORY"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEHISTORY"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" IS '发布历史';

-- ----------------------------
-- Records of "RELEASEHISTORY"
-- ----------------------------
INSERT INTO "APOLLOCONFIGDB"."RELEASEHISTORY" VALUES ('1', 'SampleApp', 'default', 'application', 'default', '1', '0', '0', '{}', '0', 'apollo', TO_DATE('2017-09-11 15:41:28', 'SYYYY-MM-DD HH24:MI:SS'), 'apollo', TO_DATE('2017-09-11 15:41:28', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for RELEASEMESSAGE
-- ----------------------------
CREATE TABLE "APOLLOCONFIGDB"."RELEASEMESSAGE" (
  "ID" NUMBER NOT NULL ,
  "MESSAGE" VARCHAR2(1024 BYTE) NOT NULL ,
  "DATACHANGE_LASTTIME" DATE NOT NULL 
)
TABLESPACE "APOLLOCONFIGDB"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEMESSAGE"."ID" IS '主键';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEMESSAGE"."MESSAGE" IS '发布的消息内容';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASEMESSAGE"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."RELEASEMESSAGE" IS '发布消息';

-- ----------------------------
-- Table structure for RELEASE_TABLE
-- ----------------------------
CREATE TABLE "APOLLOCONFIGDB"."RELEASE_TABLE" (
  "ID" NUMBER NOT NULL ,
  "RELEASEKEY" VARCHAR2(64 BYTE) NOT NULL ,
  "NAME" VARCHAR2(64 BYTE) DEFAULT 'default'  NOT NULL ,
  "COMMT" VARCHAR2(256 BYTE) ,
  "APPID" VARCHAR2(500 BYTE) DEFAULT 'default'  NOT NULL ,
  "CLUSTERNAME" VARCHAR2(500 BYTE) DEFAULT 'default'  NOT NULL ,
  "NAMESPACENAME" VARCHAR2(500 BYTE) DEFAULT 'default'  NOT NULL ,
  "CONFIGURATIONS" CLOB ,
  "ISABANDONED" NUMBER(3) DEFAULT 0  NOT NULL ,
  "ISDELETED" NUMBER(3) DEFAULT 0  NOT NULL ,
  "DATACHANGE_CREATEDBY" VARCHAR2(32 BYTE) ,
  "DATACHANGE_CREATEDTIME" DATE NOT NULL ,
  "DATACHANGE_LASTMODIFIEDBY" VARCHAR2(32 BYTE) ,
  "DATACHANGE_LASTTIME" DATE 
)
TABLESPACE "APOLLOCONFIGDB"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASE_TABLE"."ID" IS '主键';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASE_TABLE"."RELEASEKEY" IS '发布的Key';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASE_TABLE"."NAME" IS '发布名字';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASE_TABLE"."COMMT" IS '发布说明';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASE_TABLE"."APPID" IS 'AppID';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASE_TABLE"."CLUSTERNAME" IS 'ClusterName';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASE_TABLE"."NAMESPACENAME" IS 'namespaceName';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASE_TABLE"."CONFIGURATIONS" IS '发布配置';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASE_TABLE"."ISABANDONED" IS '是否废弃,1: abandoned, 0: normal';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASE_TABLE"."ISDELETED" IS '删除标志：1: deleted, 0: normal';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASE_TABLE"."DATACHANGE_CREATEDBY" IS '创建人';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASE_TABLE"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASE_TABLE"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人';
COMMENT ON COLUMN "APOLLOCONFIGDB"."RELEASE_TABLE"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."RELEASE_TABLE" IS '发布';

-- ----------------------------
-- Records of "RELEASE_TABLE"
-- ----------------------------
INSERT INTO "APOLLOCONFIGDB"."RELEASE_TABLE" VALUES ('1', '20161009155425-d3a0749c6e20bc15', '20161009155424-release', 'Sample发布', 'SampleApp', 'default', 'application', '{"timeout":"100"}', '0', '0', 'default', TO_DATE('2017-09-11 15:41:28', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2017-09-11 15:41:28', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for SERVERCONFIG
-- ----------------------------
CREATE TABLE "APOLLOCONFIGDB"."SERVERCONFIG" (
  "ID" NUMBER NOT NULL ,
  "KEY_COL" VARCHAR2(64 BYTE) DEFAULT 'default'  NOT NULL ,
  "CLUSTER_COL" VARCHAR2(32 BYTE) DEFAULT 'default'  NOT NULL ,
  "VALUE_COL" VARCHAR2(500 BYTE) ,
  "COMMT" VARCHAR2(1024 BYTE) ,
  "ISDELETED" NUMBER(3) DEFAULT 0  NOT NULL ,
  "DATACHANGE_CREATEDBY" VARCHAR2(32 BYTE) ,
  "DATACHANGE_CREATEDTIME" DATE NOT NULL ,
  "DATACHANGE_LASTMODIFIEDBY" VARCHAR2(32 BYTE) ,
  "DATACHANGE_LASTTIME" DATE 
)
TABLESPACE "APOLLOCONFIGDB"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."SERVERCONFIG"."ID" IS '主键';
COMMENT ON COLUMN "APOLLOCONFIGDB"."SERVERCONFIG"."KEY_COL" IS '配置项Key';
COMMENT ON COLUMN "APOLLOCONFIGDB"."SERVERCONFIG"."CLUSTER_COL" IS '配置对应的集群，default为不针对特定的集群';
COMMENT ON COLUMN "APOLLOCONFIGDB"."SERVERCONFIG"."VALUE_COL" IS '配置项值';
COMMENT ON COLUMN "APOLLOCONFIGDB"."SERVERCONFIG"."COMMT" IS '注释';
COMMENT ON COLUMN "APOLLOCONFIGDB"."SERVERCONFIG"."ISDELETED" IS '删除标志：1: deleted, 0: normal';
COMMENT ON COLUMN "APOLLOCONFIGDB"."SERVERCONFIG"."DATACHANGE_CREATEDBY" IS '创建人';
COMMENT ON COLUMN "APOLLOCONFIGDB"."SERVERCONFIG"."DATACHANGE_CREATEDTIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."SERVERCONFIG"."DATACHANGE_LASTMODIFIEDBY" IS '最后修改人';
COMMENT ON COLUMN "APOLLOCONFIGDB"."SERVERCONFIG"."DATACHANGE_LASTTIME" IS '最后修改时间';
COMMENT ON TABLE "APOLLOCONFIGDB"."SERVERCONFIG" IS '发布历史';

-- ----------------------------
-- Records of "SERVERCONFIG"
-- ----------------------------
INSERT INTO "APOLLOCONFIGDB"."SERVERCONFIG" VALUES ('1', 'eureka.service.url', 'default', 'http://127.0.0.1:8080/eureka/', 'Eureka服务Url', '0', 'default', TO_DATE('2017-09-11 15:41:26', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2017-09-12 14:41:58', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "APOLLOCONFIGDB"."SERVERCONFIG" VALUES ('2', 'namespace.lock.switch', 'default', 'false', '一次发布只能有一个人修改开关', '0', 'default', TO_DATE('2017-09-11 15:41:26', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2017-09-11 15:41:26', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "APOLLOCONFIGDB"."SERVERCONFIG" VALUES ('3', 'item.value.length.limit', 'default', '20000', 'item value最大长度限制', '0', 'default', TO_DATE('2017-09-11 15:41:26', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2017-09-11 15:41:26', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "APOLLOCONFIGDB"."SERVERCONFIG" VALUES ('4', 'appnamespace.private.enable', 'default', 'false', '是否开启private namespace', '0', 'default', TO_DATE('2017-09-11 15:41:26', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2017-09-11 15:41:26', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "APOLLOCONFIGDB"."SERVERCONFIG" VALUES ('5', 'item.key.length.limit', 'default', '128', 'item key 最大长度限制', '0', 'default', TO_DATE('2017-09-11 15:41:26', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2017-09-11 15:41:26', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for SYS_ID_MACHINE
-- ----------------------------
CREATE TABLE "APOLLOCONFIGDB"."SYS_ID_MACHINE" (
  "MACHINE_IP" NVARCHAR2(16) NOT NULL ,
  "MACHINE_ID" NUMBER(11) NOT NULL ,
  "ADD_TIME" DATE NOT NULL ,
  "HEART_LAST_TIME" DATE NOT NULL 
)
TABLESPACE "UPMS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "APOLLOCONFIGDB"."SYS_ID_MACHINE"."MACHINE_IP" IS '主机IP';
COMMENT ON COLUMN "APOLLOCONFIGDB"."SYS_ID_MACHINE"."MACHINE_ID" IS '主机IP对应的机器码';
COMMENT ON COLUMN "APOLLOCONFIGDB"."SYS_ID_MACHINE"."ADD_TIME" IS '创建时间';
COMMENT ON COLUMN "APOLLOCONFIGDB"."SYS_ID_MACHINE"."HEART_LAST_TIME" IS '最后一次心跳时间';

-- ----------------------------
-- Primary Key structure for table ACCESSKEY
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."ACCESSKEY" ADD CONSTRAINT "PRIMARY00000" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table ACCESSKEY
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."ACCESSKEY" ADD CONSTRAINT "SYS_C0028502" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ACCESSKEY" ADD CONSTRAINT "SYS_C0028503" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ACCESSKEY" ADD CONSTRAINT "SYS_C0028504" CHECK ("SECRET" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ACCESSKEY" ADD CONSTRAINT "SYS_C0028505" CHECK ("ISENABLED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ACCESSKEY" ADD CONSTRAINT "SYS_C0028506" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ACCESSKEY" ADD CONSTRAINT "SYS_C0028507" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table ACCESSKEY
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."APPID00000"
  ON "APOLLOCONFIGDB"."ACCESSKEY" ("APPID" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "APOLLOCONFIGDB"."DATACHANGE_LASTTIME00000"
  ON "APOLLOCONFIGDB"."ACCESSKEY" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Primary Key structure for table APP
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "PRIMARY00001" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table APP
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C0028509" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C0028510" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C0028511" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C0028512" CHECK ("ORGID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C0028513" CHECK ("ORGNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C0028514" CHECK ("OWNERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C0028515" CHECK ("OWNEREMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C0028516" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APP" ADD CONSTRAINT "SYS_C0028517" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table APP
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."APPID00001"
  ON "APOLLOCONFIGDB"."APP" ("APPID" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "APOLLOCONFIGDB"."DATACHANGE_LASTTIME00001"
  ON "APOLLOCONFIGDB"."APP" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Primary Key structure for table APPNAMESPACE
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."APPNAMESPACE" ADD CONSTRAINT "PRIMARY00002" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table APPNAMESPACE
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C0028519" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C0028520" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C0028521" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C0028522" CHECK ("FORMAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C0028523" CHECK ("ISPUBLIC" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C0028524" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."APPNAMESPACE" ADD CONSTRAINT "SYS_C0028525" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table APPNAMESPACE
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."DATACHANGE_LASTTIME00002"
  ON "APOLLOCONFIGDB"."APPNAMESPACE" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "APOLLOCONFIGDB"."IX_APPID"
  ON "APOLLOCONFIGDB"."APPNAMESPACE" ("APPID" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "APOLLOCONFIGDB"."NAME_APPID"
  ON "APOLLOCONFIGDB"."APPNAMESPACE" ("NAME" ASC, "APPID" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Primary Key structure for table AUDIT_TABLE
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."AUDIT_TABLE" ADD CONSTRAINT "PRIMARY00003" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table AUDIT_TABLE
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."AUDIT_TABLE" ADD CONSTRAINT "SYS_C0028527" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."AUDIT_TABLE" ADD CONSTRAINT "SYS_C0028528" CHECK ("ENTITYNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."AUDIT_TABLE" ADD CONSTRAINT "SYS_C0028529" CHECK ("OPNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."AUDIT_TABLE" ADD CONSTRAINT "SYS_C0028530" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."AUDIT_TABLE" ADD CONSTRAINT "SYS_C0028531" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table AUDIT_TABLE
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."DATACHANGE_LASTTIME00003"
  ON "APOLLOCONFIGDB"."AUDIT_TABLE" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Primary Key structure for table CLUSTER_TABLE
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."CLUSTER_TABLE" ADD CONSTRAINT "PRIMARY00004" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table CLUSTER_TABLE
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."CLUSTER_TABLE" ADD CONSTRAINT "SYS_C0028533" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."CLUSTER_TABLE" ADD CONSTRAINT "SYS_C0028534" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."CLUSTER_TABLE" ADD CONSTRAINT "SYS_C0028535" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."CLUSTER_TABLE" ADD CONSTRAINT "SYS_C0028536" CHECK ("PARENTCLUSTERID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."CLUSTER_TABLE" ADD CONSTRAINT "SYS_C0028537" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."CLUSTER_TABLE" ADD CONSTRAINT "SYS_C0028538" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table CLUSTER_TABLE
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."DATACHANGE_LASTTIME00004"
  ON "APOLLOCONFIGDB"."CLUSTER_TABLE" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "APOLLOCONFIGDB"."IX_APPID_NAME"
  ON "APOLLOCONFIGDB"."CLUSTER_TABLE" ("APPID" ASC, "NAME" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "APOLLOCONFIGDB"."IX_PARENTCLUSTERID"
  ON "APOLLOCONFIGDB"."CLUSTER_TABLE" ("PARENTCLUSTERID" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Primary Key structure for table COMMIT
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."COMMIT" ADD CONSTRAINT "PRIMARY00005" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table COMMIT
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."COMMIT" ADD CONSTRAINT "SYS_C0028540" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."COMMIT" ADD CONSTRAINT "SYS_C0028541" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."COMMIT" ADD CONSTRAINT "SYS_C0028542" CHECK ("CLUSTERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."COMMIT" ADD CONSTRAINT "SYS_C0028543" CHECK ("NAMESPACENAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."COMMIT" ADD CONSTRAINT "SYS_C0028544" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."COMMIT" ADD CONSTRAINT "SYS_C0028545" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table COMMIT
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."APPID00005"
  ON "APOLLOCONFIGDB"."COMMIT" ("APPID" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "APOLLOCONFIGDB"."CLUSTERNAME"
  ON "APOLLOCONFIGDB"."COMMIT" ("CLUSTERNAME" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "APOLLOCONFIGDB"."DATACHANGE_LASTTIME00005"
  ON "APOLLOCONFIGDB"."COMMIT" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "APOLLOCONFIGDB"."NAMESPACENAME"
  ON "APOLLOCONFIGDB"."COMMIT" ("NAMESPACENAME" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Primary Key structure for table GRAYRELEASERULE
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" ADD CONSTRAINT "PRIMARY00006" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table GRAYRELEASERULE
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" ADD CONSTRAINT "SYS_C0028547" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" ADD CONSTRAINT "SYS_C0028548" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" ADD CONSTRAINT "SYS_C0028549" CHECK ("CLUSTERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" ADD CONSTRAINT "SYS_C0028550" CHECK ("NAMESPACENAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" ADD CONSTRAINT "SYS_C0028551" CHECK ("BRANCHNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" ADD CONSTRAINT "SYS_C0028552" CHECK ("RELEASEID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" ADD CONSTRAINT "SYS_C0028553" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."GRAYRELEASERULE" ADD CONSTRAINT "SYS_C0028555" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table GRAYRELEASERULE
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."DATACHANGE_LASTTIME00006"
  ON "APOLLOCONFIGDB"."GRAYRELEASERULE" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "APOLLOCONFIGDB"."IX_NAMESPACE"
  ON "APOLLOCONFIGDB"."GRAYRELEASERULE" ("CLUSTERNAME" ASC, "NAMESPACENAME" ASC, "APPID" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Primary Key structure for table INSTANCE
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."INSTANCE" ADD CONSTRAINT "PRIMARY00007" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table INSTANCE
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."INSTANCE" ADD CONSTRAINT "SYS_C0028557" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCE" ADD CONSTRAINT "SYS_C0028558" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCE" ADD CONSTRAINT "SYS_C0028559" CHECK ("CLUSTERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCE" ADD CONSTRAINT "SYS_C0028560" CHECK ("IP" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCE" ADD CONSTRAINT "SYS_C0028561" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCE" ADD CONSTRAINT "SYS_C0028562" CHECK ("DATACHANGE_LASTTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table INSTANCE
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."DATACHANGE_LASTTIME00007"
  ON "APOLLOCONFIGDB"."INSTANCE" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "APOLLOCONFIGDB"."IX_IP"
  ON "APOLLOCONFIGDB"."INSTANCE" ("IP" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE UNIQUE INDEX "APOLLOCONFIGDB"."IX_UNIQUE_KEY"
  ON "APOLLOCONFIGDB"."INSTANCE" (CASE  WHEN ("APPID" IS NOT NULL AND "CLUSTERNAME" IS NOT NULL AND "IP" IS NOT NULL AND "DATACENTER" IS NOT NULL) THEN SYS_OP_C2C("APPID")||U', '||SYS_OP_C2C("CLUSTERNAME")||U', '||SYS_OP_C2C("IP")||U', '||SYS_OP_C2C("DATACENTER") END  ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Primary Key structure for table INSTANCECONFIG
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."INSTANCECONFIG" ADD CONSTRAINT "PRIMARY00008" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table INSTANCECONFIG
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."INSTANCECONFIG" ADD CONSTRAINT "SYS_C0028564" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCECONFIG" ADD CONSTRAINT "SYS_C0028565" CHECK ("CONFIGAPPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCECONFIG" ADD CONSTRAINT "SYS_C0028566" CHECK ("CONFIGCLUSTERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCECONFIG" ADD CONSTRAINT "SYS_C0028567" CHECK ("CONFIGNAMESPACENAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCECONFIG" ADD CONSTRAINT "SYS_C0028568" CHECK ("RELEASEKEY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCECONFIG" ADD CONSTRAINT "SYS_C0028569" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."INSTANCECONFIG" ADD CONSTRAINT "SYS_C0028570" CHECK ("DATACHANGE_LASTTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table INSTANCECONFIG
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."IX_DATACHANGE_LASTTIME00008"
  ON "APOLLOCONFIGDB"."INSTANCECONFIG" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "APOLLOCONFIGDB"."IX_RELEASEKEY"
  ON "APOLLOCONFIGDB"."INSTANCECONFIG" ("RELEASEKEY" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE UNIQUE INDEX "APOLLOCONFIGDB"."IX_UNIQUE_KEY00008"
  ON "APOLLOCONFIGDB"."INSTANCECONFIG" (CASE  WHEN ("INSTANCEID" IS NOT NULL AND "CONFIGAPPID" IS NOT NULL AND "CONFIGNAMESPACENAME" IS NOT NULL) THEN SYS_OP_C2C(TO_CHAR("INSTANCEID")||',')||SYS_OP_C2C("CONFIGAPPID")||U', '||SYS_OP_C2C("CONFIGNAMESPACENAME") END  ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "APOLLOCONFIGDB"."IX_VALID_NAMESPACE"
  ON "APOLLOCONFIGDB"."INSTANCECONFIG" ("CONFIGNAMESPACENAME" ASC, "CONFIGCLUSTERNAME" ASC, "DATACHANGE_LASTTIME" ASC, "CONFIGAPPID" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Primary Key structure for table ITEM
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."ITEM" ADD CONSTRAINT "PRIMARY00009" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table ITEM
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."ITEM" ADD CONSTRAINT "SYS_C0028572" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ITEM" ADD CONSTRAINT "SYS_C0028573" CHECK ("NAMESPACEID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ITEM" ADD CONSTRAINT "SYS_C0028574" CHECK ("KEY_COL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ITEM" ADD CONSTRAINT "SYS_C0028575" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."ITEM" ADD CONSTRAINT "SYS_C0028576" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table ITEM
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."DATACHANGE_LASTTIME00009"
  ON "APOLLOCONFIGDB"."ITEM" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "APOLLOCONFIGDB"."IX_GROUPID"
  ON "APOLLOCONFIGDB"."ITEM" ("NAMESPACEID" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Primary Key structure for table NAMESPACE
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACE" ADD CONSTRAINT "PRIMARY00010" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table NAMESPACE
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACE" ADD CONSTRAINT "SYS_C0028578" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACE" ADD CONSTRAINT "SYS_C0028579" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACE" ADD CONSTRAINT "SYS_C0028580" CHECK ("CLUSTERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACE" ADD CONSTRAINT "SYS_C0028581" CHECK ("NAMESPACENAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACE" ADD CONSTRAINT "SYS_C0028582" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACE" ADD CONSTRAINT "SYS_C0028583" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACE" ADD CONSTRAINT "SYS_C0028724" CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table NAMESPACE
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."APPID_CLUSTERNAME_NAMESPACENA"
  ON "APOLLOCONFIGDB"."NAMESPACE" ("APPID" ASC, "CLUSTERNAME" ASC, "NAMESPACENAME" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "APOLLOCONFIGDB"."DATACHANGE_LASTTIME00010"
  ON "APOLLOCONFIGDB"."NAMESPACE" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "APOLLOCONFIGDB"."IX_NAMESPACENAME"
  ON "APOLLOCONFIGDB"."NAMESPACE" ("NAMESPACENAME" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Primary Key structure for table NAMESPACELOCK
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACELOCK" ADD CONSTRAINT "PRIMARY00011" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table NAMESPACELOCK
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACELOCK" ADD CONSTRAINT "SYS_C0028585" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACELOCK" ADD CONSTRAINT "SYS_C0028586" CHECK ("NAMESPACEID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACELOCK" ADD CONSTRAINT "SYS_C0028587" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."NAMESPACELOCK" ADD CONSTRAINT "SYS_C0028588" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table NAMESPACELOCK
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."DATACHANGE_LASTTIME00011"
  ON "APOLLOCONFIGDB"."NAMESPACELOCK" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE UNIQUE INDEX "APOLLOCONFIGDB"."IX_NAMESPACEID"
  ON "APOLLOCONFIGDB"."NAMESPACELOCK" ("CASE  WHEN "NAMESPACEID" IS NOT NULL THEN "NAMESPACEID" END " ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Primary Key structure for table RELEASEHISTORY
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "PRIMARY00014" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table RELEASEHISTORY
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C0028604" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C0028605" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C0028606" CHECK ("CLUSTERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C0028607" CHECK ("NAMESPACENAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C0028608" CHECK ("BRANCHNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C0028609" CHECK ("RELEASEID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C0028610" CHECK ("PREVIOUSRELEASEID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C0028611" CHECK ("OPERATION" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C0028612" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEHISTORY" ADD CONSTRAINT "SYS_C0028613" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table RELEASEHISTORY
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."DATACHANGE_LASTTIME00014"
  ON "APOLLOCONFIGDB"."RELEASEHISTORY" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "APOLLOCONFIGDB"."IX_NAMESPACE00014"
  ON "APOLLOCONFIGDB"."RELEASEHISTORY" ("APPID" ASC, "CLUSTERNAME" ASC, "NAMESPACENAME" ASC, "BRANCHNAME" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "APOLLOCONFIGDB"."IX_RELEASEID"
  ON "APOLLOCONFIGDB"."RELEASEHISTORY" ("RELEASEID" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Primary Key structure for table RELEASEMESSAGE
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."RELEASEMESSAGE" ADD CONSTRAINT "PRIMARY00013" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table RELEASEMESSAGE
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."RELEASEMESSAGE" ADD CONSTRAINT "SYS_C0028600" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEMESSAGE" ADD CONSTRAINT "SYS_C0028601" CHECK ("MESSAGE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASEMESSAGE" ADD CONSTRAINT "SYS_C0028602" CHECK ("DATACHANGE_LASTTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table RELEASEMESSAGE
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."DATACHANGE_LASTTIME00013"
  ON "APOLLOCONFIGDB"."RELEASEMESSAGE" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "APOLLOCONFIGDB"."IX_MESSAGE"
  ON "APOLLOCONFIGDB"."RELEASEMESSAGE" ("MESSAGE" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Primary Key structure for table RELEASE_TABLE
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."RELEASE_TABLE" ADD CONSTRAINT "PRIMARY00012" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table RELEASE_TABLE
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."RELEASE_TABLE" ADD CONSTRAINT "SYS_C0028590" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE_TABLE" ADD CONSTRAINT "SYS_C0028591" CHECK ("RELEASEKEY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE_TABLE" ADD CONSTRAINT "SYS_C0028592" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE_TABLE" ADD CONSTRAINT "SYS_C0028593" CHECK ("APPID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE_TABLE" ADD CONSTRAINT "SYS_C0028594" CHECK ("CLUSTERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE_TABLE" ADD CONSTRAINT "SYS_C0028595" CHECK ("NAMESPACENAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE_TABLE" ADD CONSTRAINT "SYS_C0028596" CHECK ("ISABANDONED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE_TABLE" ADD CONSTRAINT "SYS_C0028597" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."RELEASE_TABLE" ADD CONSTRAINT "SYS_C0028598" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table RELEASE_TABLE
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."APPID_CLUSTERNAME_GROUPNAME"
  ON "APOLLOCONFIGDB"."RELEASE_TABLE" ("APPID" ASC, "CLUSTERNAME" ASC, "NAMESPACENAME" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "APOLLOCONFIGDB"."DATACHANGE_LASTTIME00012"
  ON "APOLLOCONFIGDB"."RELEASE_TABLE" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "APOLLOCONFIGDB"."IX_RELEASEKEY00012"
  ON "APOLLOCONFIGDB"."RELEASE_TABLE" ("RELEASEKEY" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Primary Key structure for table SERVERCONFIG
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."SERVERCONFIG" ADD CONSTRAINT "PRIMARY00015" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table SERVERCONFIG
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."SERVERCONFIG" ADD CONSTRAINT "SYS_C0028615" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."SERVERCONFIG" ADD CONSTRAINT "SYS_C0028616" CHECK ("KEY_COL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."SERVERCONFIG" ADD CONSTRAINT "SYS_C0028617" CHECK ("CLUSTER_COL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."SERVERCONFIG" ADD CONSTRAINT "SYS_C0028618" CHECK ("ISDELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."SERVERCONFIG" ADD CONSTRAINT "SYS_C0028619" CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table SERVERCONFIG
-- ----------------------------
CREATE INDEX "APOLLOCONFIGDB"."DATACHANGE_LASTTIME00015"
  ON "APOLLOCONFIGDB"."SERVERCONFIG" ("DATACHANGE_LASTTIME" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "APOLLOCONFIGDB"."IX_KEY"
  ON "APOLLOCONFIGDB"."SERVERCONFIG" ("KEY_COL" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Checks structure for table SYS_ID_MACHINE
-- ----------------------------
ALTER TABLE "APOLLOCONFIGDB"."SYS_ID_MACHINE" ADD CONSTRAINT "SYS_C0026687" CHECK ("MACHINE_IP" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."SYS_ID_MACHINE" ADD CONSTRAINT "SYS_C0026688" CHECK ("MACHINE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."SYS_ID_MACHINE" ADD CONSTRAINT "SYS_C0026689" CHECK ("ADD_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."SYS_ID_MACHINE" ADD CONSTRAINT "SYS_C0026690" CHECK ("HEART_LAST_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."SYS_ID_MACHINE" ADD CONSTRAINT "SYS_C0028622" CHECK ("MACHINE_IP" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."SYS_ID_MACHINE" ADD CONSTRAINT "SYS_C0028623" CHECK ("MACHINE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."SYS_ID_MACHINE" ADD CONSTRAINT "SYS_C0028624" CHECK ("ADD_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."SYS_ID_MACHINE" ADD CONSTRAINT "SYS_C0028625" CHECK ("HEART_LAST_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."SYS_ID_MACHINE" ADD CONSTRAINT "SYS_C0028706" CHECK ("MACHINE_IP" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."SYS_ID_MACHINE" ADD CONSTRAINT "SYS_C0028707" CHECK ("MACHINE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."SYS_ID_MACHINE" ADD CONSTRAINT "SYS_C0028708" CHECK ("ADD_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "APOLLOCONFIGDB"."SYS_ID_MACHINE" ADD CONSTRAINT "SYS_C0028709" CHECK ("HEART_LAST_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table SYS_ID_MACHINE
-- ----------------------------
CREATE UNIQUE INDEX "APOLLOCONFIGDB"."SYS_ID_MACHINE_INDEX_IP"
  ON "APOLLOCONFIGDB"."SYS_ID_MACHINE" ("MACHINE_IP" ASC)
  LOGGING
  TABLESPACE "APOLLOCONFIGDB"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
